#!/usr/bin/env python3
"""
Discovered regression tests — auto-generated by freeform_bench.py.

These tests prevent specific mistakes from recurring.
Run: PYTHONPATH=src python tests/test_freeform_discovered.py
"""

import os, sys, re

_SRC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src")
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

from cos.nlg.pipeline import naturalize
from cos.nlg.config import NLGConfig

_t = 0; _p = 0; _f = 0
def suite(name):
    print(f"\n  Suite: {name}")
def check(n, c, d=""):
    global _t, _p, _f; _t += 1
    if c: _p += 1; print(f"    \u2713 {n}")
    else: _f += 1; print(f"    \u2717 {n}" + (f"\n        {d}" if d else ""))

def test_discovered_write_a_python_function_that_takes_a_lis():
    """Auto-discovered: The user specifically requested the list be sorted in reverse order, but the ass"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a Python function that takes a list of strings, filters out the ones shorter than 5 characters, and returns them sorted alphabetically in reverse order.", "", "", "factual", cfg)
    check(
        "response should not contain \"sorting the result alphabetically\"",
        "sorting the result alphabetically" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_python_function_that_takes_a_lis_1():
    """Auto-discovered: The assistant introduced a deduplication requirement that was not requested by t"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a Python function that takes a list of strings, filters out the ones shorter than 5 characters, and returns them sorted alphabetically in reverse order.", "", "", "factual", cfg)
    check(
        "response should not contain \"eliminating duplicates\"",
        "eliminating duplicates" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_tell_me_about_the_most_mysterious_unsolv():
    """Auto-discovered: The user asked for 'the most mysterious' (singular), but the assistant provided """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Tell me about the most mysterious unsolved archaeological site in the world.", "", "", "factual", cfg)
    check(
        "response should not contain \"Among the most famous is the Great Pyram\"",
        "Among the most famous is the Great Pyramid of Giza" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_comprehensive_essay_on_the_ethic():
    """Auto-discovered: The assistant provided a short summary instead of a comprehensive essay as reque"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a comprehensive essay on the ethical implications of CRISPR gene editing. Ensure you cover the potential for eliminating hereditary diseases, the risk of \"designer babies,\" and the socio-economic divide it might create.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_causes_the_fresh_rain_smell_after_a():
    """Auto-discovered: The response fails to explain the physical mechanism (aerosolization) that actua"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What causes the \"fresh rain\" smell after a storm?", "", "", "factual", cfg)
    check(
        "response should not contain \"When rain falls on dry soil, it releases\"",
        "When rain falls on dry soil, it releases geosmin and plant oils" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_per():
    """Auto-discovered: The closing tag for the header container is missing the angle bracket for the op"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a personal portfolio. Use a dark-mode aesthetic with neon accents, a responsive three-column layout for projects, and a sticky navigation bar.", "", "", "factual", cfg)
    check(
        "response should not contain \"</div>\"",
        "</div>" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_per_6():
    """Auto-discovered: The closing tag for the services grid is missing the closing angle bracket."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a personal portfolio. Use a dark-mode aesthetic with neon accents, a responsive three-column layout for projects, and a sticky navigation bar.", "", "", "factual", cfg)
    check(
        "response should not contain \"</div>\"",
        "</div>" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_per_7():
    """Auto-discovered: The closing tag for the masonry gallery is missing the closing angle bracket."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a personal portfolio. Use a dark-mode aesthetic with neon accents, a responsive three-column layout for projects, and a sticky navigation bar.", "", "", "factual", cfg)
    check(
        "response should not contain \"</div>\"",
        "</div>" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_per_8():
    """Auto-discovered: The closing footer tag is missing the closing angle bracket."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a personal portfolio. Use a dark-mode aesthetic with neon accents, a responsive three-column layout for projects, and a sticky navigation bar.", "", "", "factual", cfg)
    check(
        "response should not contain \"</footer\"",
        "</footer" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_per_9():
    """Auto-discovered: The closing body tag is missing the closing angle bracket."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a personal portfolio. Use a dark-mode aesthetic with neon accents, a responsive three-column layout for projects, and a sticky navigation bar.", "", "", "factual", cfg)
    check(
        "response should not contain \"</body\"",
        "</body" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_per_10():
    """Auto-discovered: The closing html tag is missing the closing angle bracket."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a personal portfolio. Use a dark-mode aesthetic with neon accents, a responsive three-column layout for projects, and a sticky navigation bar.", "", "", "factual", cfg)
    check(
        "response should not contain \"</html\"",
        "</html" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_per_11():
    """Auto-discovered: The user requested 'neon accents', but the assistant used a muted pastel blue, w"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a personal portfolio. Use a dark-mode aesthetic with neon accents, a responsive three-column layout for projects, and a sticky navigation bar.", "", "", "factual", cfg)
    check(
        "response should not contain \"color: #8ab4f8;\"",
        "color: #8ab4f8;" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_to_implement_a_basic_binary_search_t():
    """Auto-discovered: The user asked 'How to implement', which in a programming context requires code """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How to implement a basic binary search tree in Java?", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_detailed_explanation_of_how_bl():
    """Auto-discovered: The user asked for 'current theories on Hawking radiation'. The response mention"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a detailed explanation of how black holes work, including the role of the event horizon, the concept of spaghettification, and the current theories on Hawking radiation.", "", "", "factual", cfg)
    check(
        "response should not contain \"Stephen Hawking predicted that black hol\"",
        "Stephen Hawking predicted that black holes emit radiation" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_who_is_credited_with_inventing_the_first():
    """Auto-discovered: The response provides a definition of a computer instead of answering who invent"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Who is credited with inventing the first programmable computer?", "", "", "factual", cfg)
    check(
        "response should not contain \"A computer is a machine that can be prog\"",
        "A computer is a machine that can be programmed..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_in_python_that_calculat():
    """Auto-discovered: The function calculates the nth Fibonacci number, not the sequence up to n terms"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function in Python that calculates the Fibonacci sequence up to n terms and returns the result as a list.", "", "", "factual", cfg)
    check(
        "response should not contain \"def fibonacci_memo(n, memo=None):\"",
        "def fibonacci_memo(n, memo=None):" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_in_python_that_calculat_16():
    """Auto-discovered: The function calculates the nth Fibonacci number, not the sequence up to n terms"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function in Python that calculates the Fibonacci sequence up to n terms and returns the result as a list.", "", "", "factual", cfg)
    check(
        "response should not contain \"def fibonacci_iterative(n):\"",
        "def fibonacci_iterative(n):" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_in_python_that_calculat_17():
    """Auto-discovered: While the logic uses O(1) auxiliary space, the user specifically asked for a lis"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function in Python that calculates the Fibonacci sequence up to n terms and returns the result as a list.", "", "", "factual", cfg)
    check(
        "response should not contain \"The iterative version uses O(1) space.\"",
        "The iterative version uses O(1) space." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_comparative_essay_on_st():
    """Auto-discovered: The assistant failed to write a comparative essay, omitted all information regar"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed comparative essay on Stoicism and Epicureanism. Make sure to analyze their differing views on pleasure, their approach to dealing with emotional distress, and how each philosophy defines a \"good life.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_breakdown_of_the():
    """Auto-discovered: The response describes a city in Croatia instead of explaining the fall of the R"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive breakdown of the fall of the Roman Empire, including the role of barbarian invasions, the economic instability of the 3rd century, and the impact of the split between the Eastern and Western empires.", "", "", "factual", cfg)
    check(
        "response should not contain \"Split is the second-largest city in Croa\"",
        "Split is the second-largest city in Croatia" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_breakdown_of_the_20():
    """Auto-discovered: Missing all requested information regarding barbarian invasions, economic instab"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive breakdown of the fall of the Roman Empire, including the role of barbarian invasions, the economic instability of the 3rd century, and the impact of the split between the Eastern and Western empires.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_do_i_create_a_custom_hook_in_react_t():
    """Auto-discovered: The assistant provided a data fetching hook instead of a local storage synchroni"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How do I create a custom hook in React to handle local storage synchronization?", "", "", "factual", cfg)
    check(
        "response should not contain \"Here is a robust `useFetch` custom hook \"",
        "Here is a robust `useFetch` custom hook example:" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_do_i_create_a_custom_hook_in_react_t_22():
    """Auto-discovered: The response contains zero information regarding local storage or synchronizatio"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How do I create a custom hook in React to handle local storage synchronization?", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_in_python_that_scrapes():
    """Auto-discovered: The assistant provided a CSV summary tool instead of a web scraper for H1/H2 tag"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function in Python that scrapes a website for all its H1 and H2 tags and saves them into a CSV file.", "", "", "factual", cfg)
    check(
        "response should not contain \"Here's a Python function that reads a CS\"",
        "Here's a Python function that reads a CSV file, processes the data, and generate" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_in_python_that_scrapes_24():
    """Auto-discovered: The response contains no code for web scraping, HTML parsing, or saving scraped """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function in Python that scrapes a website for all its H1 and H2 tags and saves them into a CSV file.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire code block\"",
        "The entire code block" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_analysis_of_the_fermi_p():
    """Auto-discovered: The response is a single-sentence definition and fails to provide the 'detailed """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed analysis of the \"Fermi Paradox.\" Please explain the Great Filter theory, the Zoo hypothesis, and why the lack of alien signals is so unsettling to astronomers.", "", "", "factual", cfg)
    check(
        "response should not contain \"The Fermi paradox is the apparent incons\"",
        "The Fermi paradox is the apparent inconsistency..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_fut():
    """Auto-discovered: The AI used a generic 'About [Topic]' template, treating the prompt title as the"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a futuristic city guide. Use a glassmorphism style for the cards, a sidebar for navigation, and a JavaScript-powered search bar that filters through a list of landmarks.", "", "", "factual", cfg)
    check(
        "response should not contain \"Discover the story of A Futuristic City \"",
        "Discover the story of A Futuristic City Guide" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_file_html_page_for_a_fut_27():
    """Auto-discovered: The content is repetitive and contains no actual information."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-file HTML page for a futuristic city guide. Use a glassmorphism style for the cards, a sidebar for navigation, and a JavaScript-powered search bar that filters through a list of landmarks.", "", "", "factual", cfg)
    check(
        "response should not contain \"<h3 style=\"color:#8ab4f8;\">Historical \"",
        "<h3 style=\"color:#8ab4f8;\">Historical Background</h3><p style=\"color:#bbb;\">Hist" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_to_implement_a_custom_undo_redo_syst():
    """Auto-discovered: The assistant used the wrong programming language. The user requested C#, but th"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How to implement a custom undo/redo system using the Command pattern in C#?", "", "", "factual", cfg)
    check(
        "response should not contain \"implement a basic undo/redo system using\"",
        "implement a basic undo/redo system using the Command design pattern in Python" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_is_it_that_some_people_can_remember():
    """Auto-discovered: The response does not address the user's question about memory and cognitive dif"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why is it that some people can remember every detail of their lives while others forget what they ate for breakfast?", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_is_it_that_some_people_can_remember_30():
    """Auto-discovered: The word 'History' appears as a standalone header without formatting, creating a"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why is it that some people can remember every detail of their lives while others forget what they ate for breakfast?", "", "", "factual", cfg)
    check(
        "response should not contain \"worldwide. History\"",
        "worldwide. History" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_guide_on_how_to():
    """Auto-discovered: The assistant provided a guide for soil-based urban gardening instead of hydropo"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive guide on how to start a hydroponic garden at home. Include a comparison of deep water culture vs. nutrient film technique, a list of essential minerals for the water, and a troubleshooting guide for common algae growth.", "", "", "factual", cfg)
    check(
        "response should not contain \"Urban gardening is the practice of growi\"",
        "Urban gardening is the practice of growing plants in city environments" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_guide_on_how_to_32():
    """Auto-discovered: Missing comparison of deep water culture vs. nutrient film technique."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive guide on how to start a hydroponic garden at home. Include a comparison of deep water culture vs. nutrient film technique, a list of essential minerals for the water, and a troubleshooting guide for common algae growth.", "", "", "factual", cfg)
    check(
        "response should not contain \"Entire response\"",
        "Entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_guide_on_how_to_33():
    """Auto-discovered: Missing the list of essential minerals for hydroponic water."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive guide on how to start a hydroponic garden at home. Include a comparison of deep water culture vs. nutrient film technique, a list of essential minerals for the water, and a troubleshooting guide for common algae growth.", "", "", "factual", cfg)
    check(
        "response should not contain \"Entire response\"",
        "Entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_guide_on_how_to_34():
    """Auto-discovered: Missing the troubleshooting guide for common algae growth."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive guide on how to start a hydroponic garden at home. Include a comparison of deep water culture vs. nutrient film technique, a list of essential minerals for the water, and a troubleshooting guide for common algae growth.", "", "", "factual", cfg)
    check(
        "response should not contain \"Entire response\"",
        "Entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_guide_on_how_to_35():
    """Auto-discovered: Potting mix is for soil gardening; hydroponics requires inert media like rockwoo"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive guide on how to start a hydroponic garden at home. Include a comparison of deep water culture vs. nutrient film technique, a list of essential minerals for the water, and a troubleshooting guide for common algae growth.", "", "", "factual", cfg)
    check(
        "response should not contain \"use a quality potting mix with perlite o\"",
        "use a quality potting mix with perlite or vermiculite" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_does_the_ship_of_theseus_thought_exp():
    """Auto-discovered: The Ship of Theseus and mind uploading is a widely discussed philosophical inter"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How does the \"Ship of Theseus\" thought experiment apply to modern ideas about digital consciousness and mind uploading?", "", "", "factual", cfg)
    check(
        "response should not contain \"I couldn't find solid information about \"",
        "I couldn't find solid information about that specific topic" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_does_the_ship_of_theseus_thought_exp_37():
    """Auto-discovered: The assistant used a generic refusal template that includes irrelevant instructi"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How does the \"Ship of Theseus\" thought experiment apply to modern ideas about digital consciousness and mind uploading?", "", "", "factual", cfg)
    check(
        "response should not contain \"If this was a coding question, tell me t\"",
        "If this was a coding question, tell me the language and what you're trying to do" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_does_the_ship_of_theseus_thought_exp_38():
    """Auto-discovered: The response fails to address the core of the user's question regarding digital """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How does the \"Ship of Theseus\" thought experiment apply to modern ideas about digital consciousness and mind uploading?", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )


# Run
print(f"\n{"#"*60}\n  Discovered Regression Tests\n{"#"*60}")
suite("Freeform discovered bugs")

# Execute all test functions
_test_funcs = [v for k, v in sorted(globals().items()) if k.startswith("test_discovered_")]
for _fn in _test_funcs:
    _fn()

print(f"\n  Results: {_p}/{_t} passed" + (f", {_f} FAILED" if _f else ""))
sys.exit(1 if _f else 0)
