#!/usr/bin/env python3
"""Benchmark for the rule-based text editor — pushes it to its limits.

Three groups:

  POSITIVE  — inputs that SHOULD be changed; checks the edited output contains
              an expected substring and not a forbidden one.
  NEGATIVE  — inputs that must be left UNCHANGED (or changed only by trailing
              whitespace/case-strip); catches false positives (correcting
              correct text, mangling proper nouns, URLs, decimals, etc.).
  DETECT    — edit-command phrasing -> expected (kind, content).

Run with:  python3 tests/test_editor_bench.py
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))
import cos.engine as engine
import cos.code_knowledge as code_knowledge
from cos.text_editor import detect_edit_request, edit_text, edit_code, edit_json
from cos.text_editor import detect_metrics_request

# Offline
engine._search_wikipedia = lambda query: (None, None)
engine._search_wikipedia_full = lambda query: (None, None)
code_knowledge._search_stack = lambda query, max_files=2: []

# ── POSITIVE: input -> (required_substrings, forbidden_substrings) ──────────
POSITIVE = [
    ("teh quick brown fox", ["the quick brown fox"], ["teh"]),
    ("i recieve your message", ["I receive your message"], ["recieve"]),
    ("it was definately worth it", ["definitely"], ["definately"]),
    ("please seperate the files", ["separate"], ["seperate"]),
    ("an error occured", ["occurred"], ["occured"]),
    ("wich one do you want", ["which"], ["wich"]),
    ("thier house is big", ["their house"], ["thier"]),
    ("send it to my adress", ["address"], ["adress"]),
    ("the lenght of the rope", ["length"], ["lenght"]),
    ("becuase it rained", ["because"], ["becuase"]),
    ("it is usefull", ["useful"], ["usefull"]),
    ("a succesful project", ["successful"], ["succesful"]),
    ("wait untill friday", ["until"], ["untill"]),
    ("keep writting", ["writing"], ["writting"]),
    ("it was writen down", ["written"], ["writen"]),
    ("the project was a success", ["success"], ["succes"]),
    ("i am confidant about it", ["confident"], ["confidant"]),
    ("the quik brown fox", ["quick"], ["quik"]),
    # contractions
    ("i dont know", ["I don't know"], ["dont"]),
    ("we cant go", ["we can't go"], ["cant"]),
    ("he wont come", ["he won't come"], ["wont"]),
    ("it isnt ready", ["it isn't ready"], ["isnt"]),
    ("i didnt see it", ["I didn't see it"], ["didnt"]),
    ("she doesnt care", ["she doesn't care"], ["doesnt"]),
    ("you shouldnt do that", ["shouldn't"], ["shouldnt"]),
    ("i cant beleive it", ["can't believe"], ["beleive"]),
    # homophones
    ("your going to love this", ["you're going to love this"], ["your going"]),
    ("your welcome", ["you're welcome"], ["your welcome"]),
    ("youre book is here", ["your book is here"], ["youre book"]),
    ("their going to the park", ["they're going to the park"], ["their going"]),
    ("there going home", ["they're going home"], ["there going"]),
    ("theyre house is big", ["their house is big"], ["theyre house"]),
    ("there car is red", ["their car is red"], ["there car"]),
    ("its a great day", ["it's a great day"], ["its a"]),
    ("its looking good", ["it's looking good"], ["its looking"]),
    ("the dog wagged its tail", ["its tail"], []),
    ("let me no what you think", ["let me know"], ["let me no"]),
    ("i no what to do", ["I know what to do"], ["i no what"]),
    ("their are three reasons", ["there are three reasons"], ["their are"]),
    ("please let me no", ["let me know"], ["let me no"]),
    # capitalization / spacing
    ("hello   world", ["hello world"], []),
    ("hello ,world", ["hello, world"], ["hello ,"]),
    ("hello . how are you", ["hello. how are you"], []),
    ("i am going home. i will return.", ["I am going home. I will return."], ["i am", "i will"]),
    ("a apple", ["an apple"], ["a apple"]),
    ("an university", ["a university"], ["an university"]),
    ("a hour ago", ["an hour ago"], ["a hour"]),
    ("an honest man", ["an honest man"], ["a honest"]),
    # multi-typo
    ("teh recieve date was wrong so i returned it", ["the receive date was wrong so I returned it"], ["teh", "recieve"]),
    # homophones added in the hardening pass
    ("i could of gone home", ["I could have gone home"], ["could of"]),
    ("he could of handled it better", ["could have handled"], ["could of handled"]),
    ("she might of seen it", ["might have seen"], ["might of"]),
    ("you should of told me", ["should have told"], ["should of"]),
    ("that is to much sugar", ["too much"], ["to much"]),
    ("this one is better then that", ["better than"], ["better then"]),
    ("back than things were easy", ["back then"], ["back than"]),
    ("i need to loose weight", ["lose weight"], ["loose weight"]),
    ("these jeans are lose on me", ["loose on me"], ["lose on"]),
    ("be quite please", ["be quiet please"], ["be quite"]),
    ("weather or not we go", ["whether or not"], ["weather or not"]),
    ("less people came than before", ["fewer people"], ["less people"]),
    ("i except the offer", ["I accept the offer"], ["except the offer"]),
    ("accept for this one", ["except for this one"], ["accept for"]),
    ("i walked passed the store", ["walked past the store"], ["walked passed"]),
    ("we had desert after dinner", ["had dessert"], ["had desert"]),
    ("i cant breath", ["can't breathe"], ["cant breath"]),
    ("take a breathe", ["take a breath"], ["take a breathe"]),
    ("ill be there soon", ["I'll be there soon"], ["ill be"]),
    ("whos there", ["who's there"], ["whos"]),
    ("wheres the file", ["where's the file"], ["wheres"]),
    ("a hour ago", ["an hour ago"], ["a hour"]),
    ("an used car", ["a used car"], ["an used"]),
    ("anyways, lets go", ["Anyway, let's go"], ["anyways"]),
    ("its important to finish on time", ["It's important"], ["its important"]),
    ("the data dosent match", ["doesn't match"], ["dosent"]),
    ("we meet on monday in january", ["Monday", "January"], ["monday", "january"]),
    # homophone wave 3
    ("the drug can effect your mood", ["affect your mood"], ["effect your"]),
    ("the affect was noticeable", ["The effect was noticeable"], ["the affect"]),
    ("that was a peace of cake", ["piece of cake"], ["peace of"]),
    ("write now, please", ["Right now"], ["write now"]),
    ("right a letter to your boss", ["Write a letter"], ["right a letter"]),
    ("she played the main roll", ["main role"], ["main roll"]),
    ("he role the dice", ["roll the dice"], ["role the dice"]),
    ("they sale the boat", ["sail the boat"], ["sale the boat"]),
    ("the house is for sail", ["for sale"], ["for sail"]),
    ("he tried to steel the show", ["steal the show"], ["steel the show"]),
    ("a bridge made of steal", ["made of steel"], ["of steal"]),
    ("i want two go home", ["to go home"], ["two go"]),
    ("me two please", ["Me too please"], ["me two"]),
    ("whose coming to the party", ["who's coming"], ["whose coming"]),
    ("that is apart of the plan", ["a part of the plan"], ["apart of"]),
    ("one upon a time", ["Once upon a time"], ["one upon"]),
    ("it maybe too late", ["it may be too late"], ["it maybe"]),
    ("may be we should go", ["Maybe we should go"], ["may be we"]),
    ("we went site seeing", ["sightseeing"], ["site seeing"]),
    ("he threw the years away", ["through the years"], ["threw the years"]),
    ("the dog wagged its tale", ["wagged its tail"], ["its tale"]),
    ("your the best", ["you're the best"], ["your the"]),
    ("its the best day ever", ["It's the best day ever"], ["its the"]),
    # typo wave 4 + sentence boundaries
    ("i'm going home now", ["I'm going home now"], ["i'm"]),
    ("hello world.this is wrong", ["Hello world. This is wrong"], ["world.this"]),
    ("what?!really", ["What?! Really"], ["?!really"]),
    ("i want some thing else", ["something else"], ["some thing"]),
    ("is any thing wrong", ["anything wrong"], ["any thing"]),
    ("every thing is fine", ["Everything is fine"], ["every thing"]),
    ("i saw some one there", ["I saw someone there"], ["some one"]),
    ("i stayed in the accomodation", ["the accommodation"], ["accomodation"]),
    ("this is intresting", ["interesting"], ["intresting"]),
    ("please write sincerly", ["sincerely"], ["sincerly"]),
    ("a colum of smoke", ["column"], ["colum"]),
    ("the govenment decided", ["government"], ["govenment"]),
    ("the project was commited on time", ["committed"], ["commited"]),
    ("he made an arguement", ["argument"], ["arguement"]),
    ("i need a vaccum cleaner", ["vacuum"], ["vaccum"]),
    ("she was particurly happy", ["particularly"], ["particurly"]),
    ("the caffiene kept me awake", ["caffeine"], ["caffiene"]),
    ("they went to the cemetary", ["cemetery"], ["cemetary"]),
    ("the guage was broken", ["gauge"], ["guage"]),
    # subject-verb agreement + comparatives
    ("there is many reasons for this", ["there are many reasons"], ["there is many"]),
    ("there is several options", ["There are several options"], ["there is several"]),
    ("i have a lots of work", ["a lot of work"], ["a lots of"]),
    ("this is more better than that", ["better than that"], ["more better"]),
    ("i seen the movie yesterday", ["I saw the movie"], ["i seen"]),
    ("i done my homework", ["I did my homework"], ["i done"]),
    ("i have saw that film", ["have seen that film"], ["have saw"]),
    ("he don't like it", ["He doesn't like it"], ["he don't"]),
    ("i doesn't understand", ["I don't understand"], ["i doesn't"]),
    ("they was happy", ["They were happy"], ["they was"]),
    ("he were late", ["He was late"], ["he were"]),
    # homophone wave 4
    ("he is the principle of the school", ["principal of the school"], ["principle of the school"]),
    ("i bought it at the stationary store", ["stationery store"], ["stationary store"]),
    ("these colors compliment each other", ["complement each other"], ["compliment each other"]),
    ("you need legal council", ["legal counsel"], ["legal council"]),
    ("please insure that the door is locked", ["ensure that"], ["insure that"]),
    ("do not brake the glass", ["break the glass"], ["brake the glass"]),
    ("she will peddle her bike to school", ["pedal her bike"], ["peddle her bike"]),
    ("he steak his claim", ["stake his claim"], ["steak his claim"]),
    ("she poured over the documents", ["pored over the documents"], ["poured over"]),
    ("my muscles are soar", ["are sore"], ["are soar"]),
    ("do not waist your time", ["waste your time"], ["waist your time"]),
    ("peak at the results", ["Peek at the results"], ["peak at"]),
    ("the bus fair went up", ["bus fare"], ["bus fair"]),
    # homophone wave 5
    ("please bare with me", ["bear with me"], ["bare with"]),
    ("the dual to the death was fierce", ["duel to the death"], ["dual to"]),
    ("she studies discreet math", ["discrete math"], ["discreet math"]),
    ("the noise can illicit a response", ["elicit a response"], ["illicit a"]),
    ("do not flaunt the rules", ["flout the rules"], ["flaunt the rules"]),
    ("we saw a grisly bear in the park", ["grizzly bear"], ["grisly bear"]),
    ("he tends to leach off his friends", ["leech off"], ["leach off"]),
    ("that is a mute point now", ["moot point"], ["mute point"]),
    ("the palette cleanser was refreshing", ["palate cleanser"], ["palette cleanser"]),
    ("it peaked my interest", ["piqued my interest"], ["peaked my"]),
    ("the speech will proceed the event", ["precede the event"], ["proceed the event"]),
    ("the doctor will proscribe medication", ["prescribe medication"], ["proscribe medication"]),
    ("we need to reign in the costs", ["rein in the costs"], ["reign in"]),
    ("it was a torturous path to the top", ["tortuous path"], ["torturous path"]),
    ("i am weary of strangers here", ["wary of strangers"], ["weary of"]),
    # transposition typos + month/day typos
    ("wiht my friend", ["With my friend"], ["wiht"]),
    ("nad then we left", ["And then we left"], ["nad"]),
    ("taht is jsut wrong", ["That is just wrong"], ["taht", "jsut"]),
    ("woudl you help", ["Would you help"], ["woudl"]),
    ("abotu the porblem", ["About the problem"], ["abotu", "porblem"]),
    ("hteir quesiton", ["Their question"], ["hteir", "quesiton"]),
    ("frist of all", ["First of all"], ["frist"]),
    ("the wrold is big", ["The world is big"], ["wrold"]),
    ("a resturant near the hotel", ["A restaurant near the hotel"], ["resturant"]),
    ("we are diferent", ["We are different"], ["diferent"]),
    ("for exmaple", ["For example"], ["exmaple"]),
    ("in janurary on tuseday", ["In January on Tuesday"], ["janurary", "tuseday"]),
    ("the meessage was short", ["The message was short"], ["meessage"]),
    ("i want somthing else", ["I want something else"], ["somthing"]),
    ("be carefull with the glass", ["Be careful with the glass"], ["carefull"]),
    ("it was a wonderfull day", ["wonderful day"], ["wonderfull"]),
    ("let us discus the plan", ["discuss the plan"], ["discus the"]),
    # homophone wave 6
    ("i here that you are coming", ["I hear that"], ["here that"]),
    ("i here about the change", ["hear about the change"], ["here about"]),
    ("hear is the file you wanted", ["Here is the file"], ["hear is"]),
    ("i herd the news yesterday", ["I heard the news"], ["herd the news"]),
    ("i herd you had a bad day", ["I heard you had"], ["herd you"]),
    ("the capitol of france is paris", ["the capital of"], ["capitol of"]),
    ("the idol threat was real", ["idle threat"], ["idol threat"]),
    ("the course sand scratched the hull", ["coarse sand"], ["course sand"]),
    ("in due coarse, the report will arrive", ["In due course"], ["due coarse"]),
    ("that was a vane attempt to win", ["vain attempt"], ["vane attempt"]),
    ("we are in the same vane here", ["in the same vein"], ["same vane"]),
    ("her soul purpose was to help", ["sole purpose"], ["soul purpose"]),
    ("he had to yolk the oxen", ["yoke the oxen"], ["yolk the oxen"]),
    ("she wanted to show her metal", ["show her mettle"], ["show her metal"]),
    ("he was a false profit", ["a false prophet"], ["false profit"]),
    ("the navel fleet set sail", ["naval fleet"], ["navel fleet"]),
    ("she has a flare for design", ["flair for design"], ["flare for"]),
    ("a horde of treasure was found", ["hoard of treasure"], ["horde of treasure"]),
    ("a hoard of zombies broke through", ["horde of zombies"], ["hoard of zombies"]),
    ("we must queue the music", ["cue the music"], ["queue the music"]),
    ("an imminent scholar visited", ["eminent scholar"], ["imminent scholar"]),
    ("he tried to insight a riot", ["incite a riot"], ["insight a riot"]),
    ("she will canvass the walls", ["canvas the walls"], ["canvass the walls"]),
    ("give me a strait answer", ["a straight answer"], ["strait answer"]),
    ("we sailed the straight of gibraltar", ["Strait of Gibraltar"], ["straight of gibraltar"]),
    ("the aircraft hanger was huge", ["aircraft hangar"], ["aircraft hanger"]),
    ("the motion censor triggered", ["motion sensor"], ["motion censor"]),
    ("a banned of brothers marched", ["band of brothers"], ["banned of"]),
    ("we played a bored game", ["board game"], ["bored game"]),
    ("welcome on bored", ["Welcome on board"], ["on bored"]),
    ("i am loathe to admit it", ["loath to admit"], ["loathe to admit"]),
    ("the team moral was low", ["team morale was low"], ["moral was"]),
    ("the principle character of the play", ["principal character"], ["principle character"]),
    ("my father taut me how to swim", ["taught me how"], ["taut me"]),
    ("a troop of actors performed", ["troupe of actors"], ["troop of actors"]),
    ("she was unphased by the news", ["unfazed"], ["unphased"]),
    ("we were not phased by the noise", ["not fazed by the noise"], ["phased by"]),
    ("it is one in the same thing", ["one and the same"], ["one in the same"]),
    ("everytime i call, it rings", ["Every time I call"], ["everytime"]),
    # new typo wave
    ("it happend yesterday", ["happened"], ["happend"]),
    ("we are amoung friends", ["among friends"], ["amoung"]),
    ("he was agressive", ["aggressive"], ["agressive"]),
    ("it was apparant to all", ["apparent"], ["apparant"]),
    ("the room was availible", ["available"], ["availible"]),
    ("a bizzare coincidence", ["bizarre"], ["bizzare"]),
    ("pick a catagory", ["category"], ["catagory"]),
    ("a changable design", ["changeable"], ["changable"]),
    ("the concensus was clear", ["consensus"], ["concensus"]),
    ("congradulations on the win", ["Congratulations"], ["congradulations"]),
    ("a curiousity about space", ["curiosity"], ["curiousity"]),
    ("the stains dissapear", ["disappear"], ["dissapear"]),
    ("dont exaggerrate the story", ["exaggerate"], ["exaggerrate"]),
    ("i have experiance with this", ["experience"], ["experiance"]),
    ("we finaly arrived", ["finally"], ["finaly"]),
    ("move foward please", ["forward"], ["foward"]),
    ("a garantee of quality", ["guarantee"], ["garantee"]),
    ("i am greatful for your help", ["grateful"], ["greatful"]),
    ("the heirarchy of needs", ["hierarchy"], ["heirarchy"]),
    ("a humerous story", ["humorous"], ["humerous"]),
    ("good hygine matters", ["hygiene"], ["hygine"]),
    ("jewlery on sale", ["jewelry"], ["jewlery"]),
    ("stop lieing to me", ["lying"], ["lieing"]),
    ("a good listner", ["listener"], ["listner"]),
    ("dont mispell that", ["misspell"], ["mispell"]),
    ("watch the moniter", ["monitor"], ["moniter"]),
    ("my neice is here", ["niece"], ["neice"]),
    ("niether option works", ["Neither"], ["niether"]),
    ("the offical report", ["official"], ["offical"]),
    ("a rare oppurtunity", ["opportunity"], ["oppurtunity"]),
    ("the parliment meets", ["parliament"], ["parliment"]),
    ("the passanger boarded", ["passenger"], ["passanger"]),
    ("i payed for it", ["paid for it"], ["payed"]),
    ("a peice of the pie", ["piece of the pie"], ["peice"]),
    ("a posession of mine", ["possession"], ["posession"]),
    ("i prefered the old one", ["preferred"], ["prefered"]),
    ("a questionaire to fill", ["questionnaire"], ["questionaire"]),
    ("i realy like it", ["really"], ["realy"]),
    ("a religous text", ["religious"], ["religous"]),
    ("sceince class", ["Science class"], ["sceince"]),
    ("a similiar case", ["similar"], ["similiar"]),
    ("sincerley yours", ["Sincerely yours"], ["sincerley"]),
    ("the strenght of steel", ["strength"], ["strenght"]),
    ("go striaght ahead", ["straight ahead"], ["striaght"]),
    ("the mission was succesfully completed", ["successfully"], ["succesfully"]),
    ("what a suprise", ["surprise"], ["suprise"]),
    ("the suround area", ["surround"], ["suround"]),
    ("a new techniqe", ["technique"], ["techniqe"]),
    ("the temperture rose", ["temperature"], ["temperture"]),
    ("lick your tounge", ["tongue"], ["tounge"]),
    ("a truely great meal", ["truly"], ["truely"]),
    ("eat your vegtables", ["vegetables"], ["vegtables"]),
    ("the vehical moved", ["vehicle"], ["vehical"]),
    ("barely visable", ["visible"], ["visable"]),
    ("withold judgement", ["Withhold"], ["withold"]),
    # grammar wave 7
    ("i suppose to go", ["I supposed to go"], ["suppose to"]),
    ("i suppost to go", ["I supposed to go"], ["suppost"]),
    ("he had went home", ["He had gone home"], ["had went"]),
    ("she couldnt of known", ["couldn't have known"], ["of known"]),
    ("for all intensive purposes it works", ["for all intents and purposes"], ["intensive purposes"]),
    ("irregardless of the cost", ["Regardless of the cost"], ["irregardless"]),
    ("in regards to your email", ["Regarding your email"], ["in regards to"]),
    ("all the sudden it rained", ["All of a sudden"], ["all the sudden"]),
    ("in the mean time, wait", ["In the meantime"], ["mean time"]),
    ("get off of the table", ["Get off the table"], ["off of"]),
    ("she is a women", ["a woman"], ["a women"]),
    ("these kind of things", ["This kind of things"], ["these kind"]),
    ("those kind of days", ["That kind of days"], ["those kind"]),
    ("between you and I", ["Between you and me"], ["and I"]),
    ("me and my friend went home", ["My friend and I went home"], ["me and my friend"]),
    ("i will defiantly be there", ["I will definitely be there"], ["defiantly"]),
    ("whos book is this", ["Whose book is this"], ["whos book"]),
    ("this is different than that", ["different from that"], ["different than"]),
    ("we assure that it works", ["We ensure that it works"], ["assure that"]),
    ("i bought it to the party", ["I brought it to the party"], ["bought it to"]),
    ("please site the source", ["Please cite the source"], ["site the source"]),
    # duplicate words
    ("the the cat sat down", ["The cat sat down"], ["the the"]),
    ("he he said no", ["He said no"], ["he he"]),
    ("and and then we left", ["And then we left"], ["and and"]),
    ("i i think so", ["I think so"], ["i i"]),
    ("lets lets go now", ["Let's go now"], ["lets lets"]),
    # typo wave 3
    ("a vaccuum cleaner", ["vacuum"], ["vaccuum"]),
    ("the commitee met", ["committee"], ["commitee"]),
    ("an embarassment to the team", ["embarrassment"], ["embarassment"]),
    ("harrasment is not ok", ["Harassment is not ok"], ["harrasment"]),
    ("her appearence was striking", ["appearance"], ["appearence"]),
    ("a facinating story", ["fascinating"], ["facinating"]),
    ("unfortunatly it rained", ["Unfortunately it rained"], ["unfortunatly"]),
    ("the seige lasted a month", ["siege"], ["seige"]),
    ("a kernal of truth", ["kernel"], ["kernal"]),
    ("i aquire new skills", ["acquire"], ["aquire"]),
    ("an allegience to the crown", ["allegiance"], ["allegience"]),
    ("amature photography", ["amateur"], ["amature"]),
    ("an artical about science", ["article"], ["artical"]),
    ("the autum leaves fell", ["autumn"], ["autum"]),
    ("benifits of exercise", ["Benefits of exercise"], ["benifits"]),
    ("decieve the reader", ["Deceive the reader"], ["decieve"]),
    ("definetly maybe", ["Definitely maybe"], ["definetly"]),
    ("dicipline is key", ["Discipline is key"], ["dicipline"]),
    ("the effecient engine", ["efficient"], ["effecient"]),
    ("enchance the image", ["Enhance the image"], ["enchance"]),
    ("an enourmous building", ["enormous"], ["enourmous"]),
    ("especialy for you", ["Especially for you"], ["especialy"]),
    ("an excellant idea", ["excellent"], ["excellant"]),
    ("exersise daily", ["Exercise daily"], ["exersise"]),
    ("an extreem sport", ["extreme"], ["extreem"]),
    ("a futher delay", ["further"], ["futher"]),
    ("i heared the news", ["I heard the news"], ["heared"]),
    ("a holliday trip", ["holiday"], ["holliday"]),
    ("imediately please", ["Immediately please"], ["imediately"]),
    ("an imposible task", ["impossible"], ["imposible"]),
    ("infromation overload", ["Information overload"], ["infromation"]),
    ("interupt the speaker", ["Interrupt the speaker"], ["interupt"]),
    ("a lawer in court", ["lawyer"], ["lawer"]),
    ("the library is open", ["library"], ["liberry"]),
    ("a lonly road", ["lonely"], ["lonly"]),
    ("the mathmatics exam", ["mathematics"], ["mathmatics"]),
    ("a millitary base", ["military"], ["millitary"]),
    ("the minumum wage", ["minimum"], ["minumum"]),
    ("a nausious feeling", ["nauseous"], ["nausious"]),
    ("necesary steps", ["Necessary steps"], ["necesary"]),
    ("nieghbor next door", ["Neighbor next door"], ["nieghbor"]),
    ("at oclock sharp", ["at o'clock"], ["oclock"]),
    ("an omited word", ["omitted"], ["omited"]),
    ("an oponent in the match", ["opponent"], ["oponent"]),
    ("a prehaps risky move", ["perhaps"], ["prehaps"]),
    ("a primative tool", ["primitive"], ["primative"]),
    ("a proffesional athlete", ["professional"], ["proffesional"]),
    ("a sandwhich for lunch", ["sandwich"], ["sandwhich"]),
    ("a satelite in orbit", ["satellite"], ["satelite"]),
    ("shedule the meeting", ["Schedule the meeting"], ["shedule"]),
    ("a smoth ride", ["smooth"], ["smoth"]),
    ("a sociaty of poets", ["society"], ["sociaty"]),
    ("the tatoo artist", ["tattoo"], ["tatoo"]),
    ("theif on the run", ["Thief on the run"], ["theif"]),
    ("go throught the door", ["go through the door"], ["throught"]),
    ("an univeristy campus", ["university"], ["univeristy"]),
    ("yesturday morning", ["Yesterday morning"], ["yesturday"]),
    # grammar wave 8
    ("he learn me to swim", ["He teach me to swim"], ["learn me"]),
    ("can you borrow me a pen", ["Can you lend me a pen"], ["borrow me"]),
    ("i didnt knew the answer", ["I didn't know the answer"], ["didnt knew"]),
    ("he doesnt knows the way", ["He doesn't know the way"], ["doesnt knows"]),
    ("i didnt saw the movie", ["I didn't see the movie"], ["didnt saw"]),
    ("i could care less", ["I couldn't care less"], ["could care less"]),
    ("im going to lay down", ["I'm going to lie down"], ["lay down"]),
    ("wait for awhile", ["Wait for a while"], ["for awhile"]),
    ("awhile ago it happened", ["A while ago it happened"], ["awhile ago"]),
    ("i go there everyday", ["I go there every day"], ["everyday"]),
    ("none the less it works", ["Nonetheless it works"], ["none the less"]),
    # typo wave 4
    ("i hadnt seen it", ["I hadn't seen it"], ["hadnt"]),
    ("itll be fine", ["It'll be fine"], ["itll"]),
    ("youd love this", ["You'd love this"], ["youd"]),
    ("theyll arrive soon", ["They'll arrive soon"], ["theyll"]),
    ("woud you help", ["Would you help"], ["woud"]),
    ("coud we start", ["Could we start"], ["coud"]),
    ("shoud i go", ["Should I go"], ["shoud"]),
    ("noone came", ["No one came"], ["noone"]),
    ("incase of fire", ["In case of fire"], ["incase"]),
    # homophone wave 9
    ("he needs to lose wait", ["lose weight"], ["lose wait"]),
    ("the wait loss program", ["weight loss program"], ["wait loss"]),
    ("weight for me outside", ["Wait for me outside"], ["weight for"]),
    ("the wolf will pray on the weak", ["prey on the weak"], ["pray on"]),
    ("we prey for peace", ["We pray for peace"], ["prey for"]),
    ("dont leek the info", ["Don't leak the info"], ["leek the"]),
    ("a flour arrangement", ["flower arrangement"], ["flour arrangement"]),
    ("a pare of shoes", ["pair of shoes"], ["pare of"]),
    ("a pear of socks", ["pair of socks"], ["pear of"]),
    ("pair the apple", ["pare the apple"], ["pair the apple"]),
    ("she road the horse", ["She rode the horse"], ["road the horse"]),
    ("the rode to town is long", ["The road to town"], ["rode to"]),
    ("two weaks from now", ["Two weeks from now"], ["weaks from now"]),
    ("a feet of engineering", ["feat of engineering"], ["feet of engineering"]),
    ("a whole in the ground", ["hole in the ground"], ["whole in"]),
    ("a hole new world", ["whole new world"], ["hole new"]),
    ("the poll vault champion", ["pole vault champion"], ["poll vault"]),
    ("he took a pole", ["he took a poll"], ["took a pole"]),
    ("a night in shining armor", ["knight in shining armor"], ["night in shining"]),
    ("eveyr day is a new day", ["Every day is a new day"], ["eveyr"]),
    ("somethign went wrong", ["Something went wrong"], ["somethign"]),
    ("i have enought time", ["I have enough time"], ["enought"]),
    # homophone wave 10
    ("can you advice me on this", ["Can you advise me on this"], ["advice me"]),
    ("that is good advise", ["That is good advice"], ["good advise"]),
    ("a new devise arrived", ["A new device arrived"], ["new devise"]),
    ("device a clever plan", ["Devise a clever plan"], ["device a clever"]),
    ("im going to lay on the bed", ["I'm going to lie on the bed"], ["lay on"]),
    ("please set down", ["Please sit down"], ["set down"]),
    ("the sight of the accident", ["The site of the accident"], ["sight of the accident"]),
    ("the queen will rain supreme", ["The queen will reign supreme"], ["rain supreme"]),
    ("a seem in the dress", ["A seam in the dress"], ["seem in"]),
    ("a sweet of rooms", ["A suite of rooms"], ["sweet of"]),
    ("suite tea please", ["Sweet tea please"], ["suite tea"]),
    # homophone wave 11
    ("the news had an affect on me", ["had an effect on me"], ["affect on"]),
    ("please ensure the car", ["Please insure the car"], ["ensure the car"]),
    ("gorilla warfare tactics", ["Guerrilla warfare tactics"], ["gorilla warfare"]),
    ("a minor working in the mines", ["A miner working in the mines"], ["minor working"]),
    ("a miner issue at work", ["A minor issue at work"], ["miner issue"]),
    ("a teem player", ["A team player"], ["teem player"]),
    ("breath deeply and relax", ["Breathe deeply and relax"], ["breath deeply"]),
    # homophone wave 13
    ("the cereal killer was caught", ["The serial killer was caught"], ["cereal killer"]),
    ("complimentary angles add to 90", ["Complementary angles"], ["complimentary angles"]),
    ("complementary tickets for the show", ["Complimentary tickets"], ["complementary tickets"]),
    ("waive at the crowd", ["Wave at the crowd"], ["waive at"]),
    ("the bank will wave the fee", ["will waive the fee"], ["wave the fee"]),
    ("an alter boy in the church", ["An altar boy"], ["alter boy"]),
    ("altar the course of history", ["Alter the course"], ["altar the course"]),
    ("currant events update", ["Current events"], ["currant events"]),
    ("a current bun for breakfast", ["A currant bun"], ["current bun"]),
    ("assent to the top of the mountain", ["Ascent to the top"], ["assent to the top"]),
    ("ascent to the plan", ["Assent to the plan"], ["ascent to the plan"]),
    ("the rope was tide to the dock", ["was tied to the dock"], ["tide to"]),
    # homophone wave 12
    ("its been a long day", ["It's been a long day"], ["its been"]),
    ("the whether report says rain", ["The weather report says rain"], ["whether report"]),
    ("two many people came", ["Too many people came"], ["two many"]),
    ("two much sugar", ["Too much sugar"], ["two much"]),
    ("two late to stop", ["Too late to stop"], ["two late"]),
]

# ── NEGATIVE: correct text that must NOT be changed ──────────────────────────
NEGATIVE = [
    "The dog wagged its tail.",
    "I went to the store to buy milk.",
    "They're going over there with their friends.",
    "You're right, your book is here.",
    "The weather is nice whether or not we go.",
    "I read a book yesterday, and I will read again tonight.",
    "He is ill today, so he will rest.",
    "Please send me to the correct address.",
    "It's a beautiful day and its beauty is stunning.",
    "NASA launched the rocket on time.",
    "McDonald's is open late.",
    "The iPhone and eBay are well-known brands.",
    "Check https://example.com or email me at user@example.com.",
    "She said, 'Hello there!' and waved.",
    "The value of pi is 3.14.",
    "The U.S. and the U.K. are both democracies.",
    "Dr. Smith, Mr. Jones, and Mrs. Lee arrived early.",
    "I have 1,000 dollars in savings.",
    "This is a unique opportunity.",
    "He drove a used car.",
    "She has a one-year plan.",
    "The hotel is on a European street.",
    "They had dinner at a restaurant.",
    "I can't wait for the weekend.",
    "Won't you come with us?",
    "Isn't it a lovely day?",
    "What's the matter?",
    "That's mine, not yours.",
    "Its owners are here now.",
    "I'd like a cup of coffee.",
    "We're going to the beach.",
    "You've been very helpful.",
    "He's the best player on the team.",
    "The children's toys are outside.",
    "James's car is parked here.",
    "Do not walk on the grass.",
    "The quick brown fox jumps over the lazy dog.",
    "E-mail me the file, please.",
    "The recipe calls for 2 cups of flour.",
    "In 2024, the company grew by 15%.",
    # false-positive guards for the hardened rules
    "He could of course come later.",
    "It will be quite cold tomorrow.",
    "It is quite interesting.",
    "He would of course know the answer.",
    "She must of course try again.",
    "I have to go to the store now.",
    "She is better than me at chess.",
    "The weather is lovely today.",
    "There are fewer people than before.",
    "The gift is except for you.",
    "He walked past the shop.",
    "They had dessert after the meal.",
    "She took a deep breath.",
    "He is ill and cannot come.",
    "I will be there soon.",
    "Who's coming to the party?",
    "Where's the nearest station?",
    "Wait an hour before calling.",
    "An hour passed slowly.",
    "He bought a used car.",
    "This is a unique and useful tool.",
    "She has a one-year contract.",
    "The U.S. dollar and the U.K. pound are currencies.",
    "E.g., apples and oranges are fruits.",
    "Mr. and Mrs. Smith attended.",
    "The meeting is at 3:30 p.m. EST.",
    "Version 2.0 ships next month.",
    "The total is $1,234.56.",
    "Dr. Lee will see you now.",
    "The meeting is on Monday in January.",
    "We may go to the park.",
    "She said it is important to try.",
    "The dog ate its food quickly.",
    # negative guards for homophone wave 3
    "The effect of the drug was clear.",
    "The medicine affected his mood.",
    "I ate a piece of cake.",
    "We should write a letter to them.",
    "She has the right answer.",
    "He played the main role in the film.",
    "Roll the dice and take a turn.",
    "The boat is for sale.",
    "They sail the boat every summer.",
    "The bridge is made of steel.",
    "He tried to steal the spotlight.",
    "I have two dogs at home.",
    "Me too, I agree with you.",
    "Whose book is this?",
    "We live apart from each other.",
    "Once upon a time, there was a dragon.",
    "Maybe we should wait.",
    "It may be too late now.",
    "We went sightseeing in the city.",
    "He threw the ball through the window.",
    "The dog wagged its tail happily.",
    "That is a tall tale.",
    "You're the best friend I have.",
    "It's the best day of the year.",
    # typo wave 4 negatives (valid British spellings and correct usage)
    "The judge gave a fair judgement.",
    "She has good judgement.",
    "They travelled across the country.",
    "The colour of the sky is blue.",
    "I realised the truth.",
    "We organised the event.",
    "The defence was strong.",
    "He cancelled the meeting.",
    "The grey cat slept.",
    "The theatre was full.",
    "This is something else entirely.",
    "Anything is possible.",
    "Everything is fine.",
    "Someone is at the door.",
    "The project was committed on time.",
    "She made a strong argument.",
    "The vacuum cleaner is new.",
    "She was particularly happy.",
    "The caffeine kept me awake.",
    "They visited the cemetery.",
    "The gauge was broken.",
    "The column of smoke rose.",
    "The government made a decision.",
    "He wrote the letter sincerely.",
    "This is interesting.",
    "The accommodation was comfortable.",
    # subject-verb agreement negatives
    "There are many reasons for this.",
    "There is one reason for this.",
    "She has a lot of work today.",
    "This is better than that.",
    "This is more interesting than that.",
    "I saw the movie yesterday.",
    "I did my homework.",
    "I have seen that film.",
    "He doesn't like it.",
    "I don't understand.",
    "They were happy.",
    "He was late.",
    "We were at home.",
    "It was a good day.",
    # homophone wave 4 negatives
    "The principle of democracy is important.",
    "The car remained stationary.",
    "She gave me a compliment.",
    "The city council met yesterday.",
    "I need to insure my car.",
    "Press the brake pedal gently.",
    "He peddles goods at the market.",
    "We shear the sheep in spring.",
    "The sheer size was impressive.",
    "I ate a steak dinner.",
    "Pour the milk over the cereal.",
    "Prices soar in summer.",
    "My waist size is 32.",
    "The mountain peak was covered in snow.",
    "That is not fair.",
    # homophone wave 5 negatives
    "The bear was large.",
    "He has a dual-core processor.",
    "She was discreet about the surprise.",
    "The police seized illicit drugs.",
    "She flaunts her wealth.",
    "The crime scene was grisly.",
    "The minerals leach into the soil.",
    "Press the mute button.",
    "The artist mixed a color palette.",
    "The mountain peak was high.",
    "Please proceed with the plan.",
    "The law proscribes violence.",
    "The king's reign lasted decades.",
    "The journey was torturous but worth it.",
    "She was weary from the long trip.",
    "Bear with me for a moment.",
    "It was a moot point after all.",
    "The bus fare is expensive.",
    "He was the principal of the school.",
    "The stationery is on the desk.",
    "The colors complement each other well.",
    "She gave me legal counsel.",
    "The company will insure the building.",
    "The brake lights are broken.",
    "He pedaled his bike uphill.",
    "She staked her claim.",
    "He pored over the book all night.",
    "My throat is sore.",
    "Do not waste water.",
    "She peeked at the results.",
    "The fare was reasonable.",
    "She was careful with the glass.",
    "It was a wonderful day.",
    "The athlete threw the discus.",
    "Let us discuss the plan tomorrow.",
    "The dress was beautiful.",
    # homophone wave 6 negatives (correct usage must stay untouched)
    "Come here and sit down.",
    "We heard a herd of cattle in the distance.",
    "The herd you see over there is ours.",
    "The capitol building is in Washington.",
    "The weather vane spun in the wind.",
    "The pop idol gave a concert.",
    "Of course you can come.",
    "The course material is dense.",
    "She found her soul mate.",
    "I ate the egg yolk.",
    "The metal detector beeped.",
    "The profit margin is thin.",
    "The navel orange was sweet.",
    "The solar flare was visible.",
    "A horde of zombies approached.",
    "The dragon guarded its hoard.",
    "People queue for tickets.",
    "Imminent danger is ahead.",
    "She gave us insight into the problem.",
    "We will canvass for votes tomorrow.",
    "Draw a straight line.",
    "The Strait of Gibraltar separates two continents.",
    "Please hang the coat on the hanger.",
    "The censor will review the film.",
    "A band of brothers marched on.",
    "The board game was fun.",
    "I am bored with this movie.",
    "I loathe spinach.",
    "The moral of the story is clear.",
    "He took the moral high ground.",
    "His moral compass guides him.",
    "The school principal spoke.",
    "The guiding principle is simple.",
    "The taut rope snapped.",
    "The troops were deployed.",
    "Phase one of the plan begins now.",
    "We get bored easily.",
    "AT&T is a large company.",
    "The old machine still works.",
    "This is the final decision.",
    "The official announcement was made.",
    # grammar wave 7 negatives (correct usage stays untouched)
    "I had had enough of the noise.",
    "He said that that was a good idea.",
    "It was very very good.",
    "No no, I don't think so.",
    "Well well, look who's here.",
    "She defiantly refused the offer.",
    "Read aloud to the class.",
    "The building site was closed.",
    "I bought it from the store.",
    "We were going home.",
    "The tool I use to write is broken.",
    "In the meantime, wait here.",
    "All of a sudden, it rained.",
    "Between me and John, there is no secret.",
    "She is a woman of integrity.",
    "This kind of thing happens.",
    "We ensure that quality is high.",
    "Please cite the source in your report.",
    "Now now, be nice.",
    "There there, it's okay.",
    # homophone wave 9 negatives (correct usage stays untouched)
    "Please wait for me.",
    "Weight loss takes time.",
    "The wolf will prey on its prey.",
    "We pray for peace every day.",
    "I ate a leek in the soup.",
    "Add flour to the mixture.",
    "A pair of shoes is on the floor.",
    "She ate a pear for lunch.",
    "He rode the horse down the road.",
    "A week from now we leave.",
    "My feet hurt after the walk.",
    "The whole thing was a success.",
    "He dug a hole in the garden.",
    "Take a poll of the class.",
    "The pole vault champion won.",
    "The knight wore shining armor.",
    # homophone wave 10 negatives (correct usage stays untouched)
    "We advise you to wait.",
    "I gave him some advice.",
    "The device is new.",
    "We will devise a plan.",
    "The papers lay on the table.",
    "Please set down the book.",
    "The sight of the city was lovely.",
    "The queen's reign lasted long.",
    "It may seem fine.",
    "Sweet of you to ask.",
    "She booked a hotel suite.",
    # homophone wave 11 negatives
    "The rain had an effect on the crops.",
    "We must ensure the project is on time.",
    "The gorilla is a large ape.",
    "The miner works underground.",
    "She is a minor in the eyes of the law.",
    "The river teems with fish.",
    "Take a deep breath.",
    "He could not breathe.",
    # homophone wave 13 negatives
    "A bowl of cereal for breakfast.",
    "The serial number is 42.",
    "Complimentary tickets were free.",
    "Complementary colors look good together.",
    "The bank will waive the fee for me.",
    "Wave at the crowd.",
    "Alter the plan if needed.",
    "The altar boy served in the church.",
    "Current events are the news.",
    "A currant bun is a sweet treat.",
    "Assent to the agreement was given.",
    "The ascent was steep and rocky.",
    "The tide of the ocean rises at night.",
    "Tied up in knots, he waited.",
    # homophone wave 12 negatives
    "It's been a good day.",
    "Whether or not we go, it will rain.",
    "The weather report is clear.",
    "Two small dogs barked at the mailman.",
    "The weather station is on the hill.",
    # grammar wave 8 negatives (correct usage stays untouched)
    "She laid down the law.",
    "Everyday life is busy.",
    "The everyday, mundane tasks took hours.",
    "He said to lay down the mat.",
    "Can I borrow your pen?",
    "I didn't see it.",
    "I don't know the answer.",
    "We were going home.",
    "Wait a while.",
    "For a while, we waited.",
]

# ── DETECT: query -> (kind, expected_content) ────────────────────────────────
DETECT = [
    ("fix this code: def add(a b): return a+b", ("code", "def add(a b): return a+b")),
    ("edit this email to fix any problems: hi there, please let me no", ("email", "hi there, please let me no")),
    ("can you fix the typos in this text: teh cat", ("text", "teh cat")),
    ("rewrite this paragraph to be more professional: so basically its good", ("text", "so basically its good")),
    ("fix this python script: for i in range(5): prnit(i)", ("code", "for i in range(5): prnit(i)")),
    ("fix the bugs in this function: def calc(x y): prnit(x+y)", ("code", "def calc(x y): prnit(x+y)")),
    ("clean up this email: hey bob , how are you", ("email", "hey bob , how are you")),
    ("fix this: teh dog ran fast", ("text", "teh dog ran fast")),
    ("fix this: \"teh cat sat down\"", ("text", "teh cat sat down")),
    ("fix this: teh \"cat\" sat", ("text", 'teh "cat" sat')),
    ("fix this code: print \"bad number\"", ("code", 'print "bad number"')),
    ("fix this python: x = 5 and prnit(x)", ("code", "x = 5 and prnit(x)")),
    ("fix the following code: def add(a b): return a+b", ("code", "def add(a b): return a+b")),
    ("fix the code below: def add(a b): return a+b", ("code", "def add(a b): return a+b")),
    ("fix this code for me: def add(a b): return a+b", ("code", "def add(a b): return a+b")),
    ("please fix the code: def add(a b): return a+b", ("code", "def add(a b): return a+b")),
    ("can you please fix this code: x = 1", ("code", "x = 1")),
    ("fix this python script: for i in range(5): prnit(i)", ("code", "for i in range(5): prnit(i)")),
    ("fix this json: {\"a\": 1,}", ("json", "{\"a\": 1,}")),
    ("fix this: {\"a\": 1 \"b\": 2}", ("json", "{\"a\": 1 \"b\": 2}")),
    ("is this json valid: {\"a\": 1}", ("json_check", "{\"a\": 1}")),
    ("is this json valid: {\"a\": }", ("json_check", "{\"a\": }")),
    ("fix the typos: i cant beleive it", ("text", "i cant beleive it")),
    ("rewrite this to fix grammar: me and my friend went", ("text", "me and my friend went")),
    ("review this email: i dont no what to say", ("email", "i dont no what to say")),
    ("whats wrong with this text: teh cat sat down", ("text", "teh cat sat down")),
    ("check this email: hi there, please let me no", ("email", "hi there, please let me no")),
    ("check my essay: the results are good", ("text", "the results are good")),
    ("proofread my essay: the results are good", ("text", "the results are good")),
    ("fix the spelling in this sentence: i dont no", ("text", "i dont no")),
    ("fix this: def add(a b): return a+b", ("code", "def add(a b): return a+b")),
    ("fix this: print('hello')", ("code", "print('hello')")),
    ("fix this: thanks for everything", ("text", "thanks for everything")),
    ("fix this: let me know if you can", ("text", "let me know if you can")),
    ("check this html: <div><p>hi</p>", ("code", "<div><p>hi</p>")),
    ("fix this html: <a herf=\"x\">link</a>", ("code", "<a herf=\"x\">link</a>")),
    ("edit this javascript function: function add(a b) { retunr a+b }", ("code", "function add(a b) { retunr a+b }")),
    # must NOT detect
    ("how do i fix this code error", None),
    ("what is the best way to edit photos", None),
    ("can you fix my computer", None),
    ("please fix the world", None),
]


# ── CODE: input -> (required_substrings, forbidden_substrings) ─────────────
CODE = [
    ("if x > 5\n    print(x)", ["if x > 5:"], ["if x > 5\n"]),
    ("def foo()\n    pass", ["def foo():"], ["def foo()\n"]),
    ("else\n    print(1)", ["else:"], ["else\n"]),
    ("try\n    risky()\nexcept Exception\n    pass", ["try:", "except Exception:"], ["try\n", "except Exception\n"]),
    ("for i in range(5)\n    print(i)", ["for i in range(5):"], ["for i in range(5)\n"]),
    ("def add(a, b):\n    return a + b", ["def add(a, b):"], []),  # clean stays clean
    ("def add(a, b): print(a+b)", ["def add(a, b): print(a+b)"], ["print(a+b):"]),  # one-liner keeps its colon
    ("def calc(x y): prnit(x+y)", ["def calc(x, y): print(x+y)"], ["def calc(x y)"]),
    ("print \"hello\"", ["print(\"hello\")"], ["print \""]),
    ("for i in xrange(10):\n    print i", ["for i in range(10):", "print(i)"], ["xrange", "print i"]),
    ("for i range(10):\n    print(i)", ["for i in range(10):"], ["for i range"]),
    ("for key, value in d.items():\n    print(key)", ["for key, value in d.items():"], ["in in"]),
    ("if x = 5:\n    print('five')", ["if x == 5:"], ["if x = 5:"]),
    ("while i = 3:\n    print(i)", ["while i == 3:"], ["while i = 3:"]),
    ("if x == 5:\n    print(x)", ["if x == 5:"], []),  # clean == stays
    ("name = raw_input(\"name: \")", ["name = input(\"name: \")"], ["raw_input"]),
    ("for k, v in d.iteritems():\n    print k", ["for k, v in d.items():"], ["iteritems"]),
    ("try:\n    risky()\nexcept ValueError, e:\n    print e", ["except ValueError as e:"], ["ValueError, e"]),
    ("print(\"hello\")", ["print(\"hello\")"], []),  # py3 clean stays
    ("SELECT * FORM users WERE id = 1", ["SELECT * FROM users WHERE id = 1"], ["FORM", "WERE"]),
    ("INERT INTO users (id) VALUES (1)", ["INSERT INTO users (id) VALUES (1)"], ["INERT"]),
    ("ecoh \"hello\"", ["echo \"hello\""], ["ecoh"]),
    ("sudu apt install python3", ["sudo apt install python3"], ["sudu"]),
    ("SELECT * FROM users", ["SELECT * FROM users"], []),  # clean sql stays
    ("<a herf=\"page.html\" clas=\"btn\">link</a>", ["<a href=\"page.html\" class=\"btn\">link</a>"], ["herf", "clas"]),
    ("<div>text</dvi>", ["<div>text</div>"], ["</dvi>"]),
    ("<a href=\"x.html\" class=\"btn\">x</a>", ["<a href=\"x.html\" class=\"btn\">x</a>"], []),  # clean html stays
    ("a {\n  color: red;\n}", ["color: red;"], []),  # css still detected
    ("def greet(name):\nreturn \"hi\"", ["def greet(name):", "    return \"hi\""], ["\nreturn"]),
    ("if x > 0:\nprint(x)", ["if x > 0:", "    print(x)"], [":\nprint"]),
    ("funtion add(a, b) { reutrn a + b }", ["function add(a, b) { return a + b }"], ["funtion", "reutrn"]),
    ("a {\n  background-colour: blue\n  pading: 16 px\n}", ["background-color: blue;", "padding: 16px;"], ["colour", "pading"]),
    ("a {\n  color red\n}", ["color: red;"], ["color red"]),
    (".box {\n  color: red;\n  margin: 10px;\n}", ["color: red;"], []),  # clean stays clean
    # code typo wave
    ("funciton add(a, b) {\n  retrun a + b\n}", ["function add(a, b) {", "return a + b"], ["funciton", "retrun"]),
    ("def f():\n    defualt = 1\n    print(defualt)", ["default = 1"], ["defualt"]),
    ("paramters = [1, 2]", ["parameters = [1, 2]"], ["paramters"]),
    ("responce = get_data()", ["response = get_data()"], ["responce"]),
    ("seach = find_all()", ["search = find_all()"], ["seach"]),
    ("objcet = {}", ["object = {}"], ["objcet"]),
    ("def f():\n    initalize()", ["initialize()"], ["initalize"]),
    ("heigth = 10", ["height = 10"], ["heigth"]),
    ("widnow = 10", ["window = 10"], ["widnow"]),
    ("my_sting = 'x'", ["my_string = 'x'"], ["my_sting"]),  # snake_case typo
    ("retrun_value = 1", ["return_value = 1"], ["retrun"]),  # snake_case typo
    ("x = 5\nif x <> 3:\n    print(x)", ["if x != 3:", "print(x)"], ["x <> 3"]),
    ("name = unicode(x)", ["name = str(x)"], ["unicode"]),
    ("def f():\n    return isinstance(x, basestring)", ["isinstance(x, str)"], ["basestring"]),
    ("d = {}\nif d.has_key(\"k\"):\n    print(\"yes\")", ["if k in d:"], ["has_key"]),
    ("d = {}\nif d.has_key(key):\n    print(\"yes\")", ["if key in d:"], ["has_key"]),
    ("doucment.getElementById('x')", ["document.getElementById('x')"], ["doucment"]),
    ("btn.addEventListner('click', fn)", ["addEventListener('click'"], ["addEventListner"]),
    ("el.textContnet = 'hi'", ["textContent"], ["textContnet"]),
    ("a {\n  box-sizng: border-box;\n}", ["box-sizing: border-box;"], ["box-sizng"]),
    ("SELEC * FORM users", ["SELECT * FROM users"], ["SELEC", "FORM"]),
    ("touh file.txt", ["touch file.txt"], ["touh"]),
    ("<div><p>hello</p>", ["</div>"], []),  # auto-close unclosed tag
    ("<div><span>x</span></div>", ["<div><span>x</span></div>"], []),  # balanced stays
    ("<ul><li>a</li><li>b</li></ul>", ["<ul><li>a</li><li>b</li></ul>"], []),  # li implicit close ok
    ("<img src=\"a.png\">", ["<img src=\"a.png\">"], []),  # void element ok
]


# ── JSON: input -> (required_substrings, forbidden_substrings) ──────────────
JSON = [
    ('{"a": 1,}', ['"a": 1'], [',}']),
    ("{'name': 'cos'}", ['"name": "cos"'], ["'name'"]),
    ('{"a":1 "b":2}', ['"a": 1,', '"b": 2'], ['1 "b"']),
    ('{name: "cos", age: 3}', ['"name": "cos"', '"age": 3'], ['{name']),
    ('{"valid": true}', ['"valid": true'], []),
]


# ── METRICS: query -> (unit, expected_content) or None ──────────────────────
METRICS = [
    ("how many words in this text: hello world", ("words", "hello world")),
    ("count the sentences: one. two. three.", ("sentences", "one. two. three.")),
    ("how many lines in this text: a\nb\nc", ("lines", "a\nb\nc")),
    ("count the letters: abcdef", ("letters", "abcdef")),
    ("how long is this text: hello there", ("length", "hello there")),
    ("count the words: the cat sat", ("words", "the cat sat")),
    ("how many words are there", None),
    ("how many words is this", None),
    ("how many words do you know", None),
]


def main():
    failures = []
    passed = 0

    # ── POSITIVE ──
    import re as _re
    for text, required, forbidden in POSITIVE:
        edited, _ = edit_text(text)
        low = edited.lower()
        missing = [r for r in required if r.lower() not in low]
        # forbidden words must not appear as WHOLE WORDS in the edited text,
        # case-sensitive ("i am" the typo vs "I am" fixed)
        bad = [f for f in forbidden if _re.search(r'\b' + _re.escape(f) + r'\b', edited)]
        if missing or bad:
            failures.append(('POS', text, edited, missing, bad))
        else:
            passed += 1

    # ── NEGATIVE ──
    for text in NEGATIVE:
        edited, _ = edit_text(text)
        if edited != text:
            failures.append(('NEG', text, edited, [], [f'changed: {text!r} -> {edited!r}']))
        else:
            passed += 1

    # ── CODE (edit_code) ──
    for text, required, forbidden in CODE:
        edited, _ = edit_code(text)
        low = edited.lower()
        missing = [r for r in required if r.lower() not in low]
        bad = [f for f in forbidden if _re.search(r'\b' + _re.escape(f.lower()) + r'\b', low)]
        if missing or bad:
            failures.append(('COD', text, edited, missing, bad))
        else:
            passed += 1

    # ── JSON (edit_json) ──
    for text, required, forbidden in JSON:
        edited, _ = edit_json(text)
        low = edited.lower()
        missing = [r for r in required if r.lower() not in low]
        bad = [f for f in forbidden if f.lower() in low]
        if missing or bad:
            failures.append(('JSN', text, edited, missing, bad))
        else:
            passed += 1

    # ── DETECT ──
    for query, expected in DETECT:
        got = detect_edit_request(query)
        if got != expected:
            failures.append(('DET', query, got, [f'expected {expected!r}'], []))
        else:
            passed += 1

    # ── METRICS ──
    for query, expected in METRICS:
        got = detect_metrics_request(query)
        if got != expected:
            failures.append(('MET', query, got, [f'expected {expected!r}'], []))
        else:
            passed += 1

    total = len(POSITIVE) + len(NEGATIVE) + len(DETECT) + len(CODE) + len(JSON) + len(METRICS)
    print(f"Results: {passed}/{total} passed")
    if failures:
        print("\nFAILURES:")
        for group, inp, out, missing, bad in failures:
            print(f"  [{group}] {inp[:70]!r}")
            if missing:
                print(f"     missing: {missing}")
            if bad:
                print(f"     bad: {bad}")
            print(f"     output: {out[:130]!r}")
        sys.exit(1)


if __name__ == '__main__':
    main()
