#!/usr/bin/env python3
"""
Discovered regression tests — auto-generated by freeform_bench.py.

These tests prevent specific mistakes from recurring.
Run: PYTHONPATH=src python tests/test_freeform_discovered.py
"""

import os, sys, re

_SRC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src")
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

from cos.nlg.pipeline import naturalize
from cos.nlg.config import NLGConfig

_t = 0; _p = 0; _f = 0
def suite(name):
    print(f"\n  Suite: {name}")
def check(n, c, d=""):
    global _t, _p, _f; _t += 1
    if c: _p += 1; print(f"    \u2713 {n}")
    else: _f += 1; print(f"    \u2717 {n}" + (f"\n        {d}" if d else ""))

def test_discovered_write_a_detailed_explanation_of_how_nucl():
    """Auto-discovered: The assistant failed to address any part of the user's request regarding nuclear"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed explanation of how nuclear fusion works, including the role of plasma, the conditions found in the sun's core, and the current progress of ITER.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_explanation_of_how_nucl_1():
    """Auto-discovered: The response cuts off abruptly at the end."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed explanation of how nuclear fusion works, including the role of plasma, the conditions found in the sun's core, and the current progress of ITER.", "", "", "factual", cfg)
    check(
        "response should not contain \"the tendency in much of the recent philo\"",
        "the tendency in much of the recent philosophical literature has been to assum" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_explanation_of_how_nucl_2():
    """Auto-discovered: Incorrect preposition usage; 'rely' should be followed by 'on'."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed explanation of how nuclear fusion works, including the role of plasma, the conditions found in the sun's core, and the current progress of ITER.", "", "", "factual", cfg)
    check(
        "response should not contain \"rely to the subject’s beliefs\"",
        "rely to the subject’s beliefs" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_python_function_that_takes_a_lis():
    """Auto-discovered: The assistant ignored the user's specific requirements (filter length < 5, upper"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a Python function that takes a list of strings, filters out those shorter than 5 characters, sorts them alphabetically, and returns the final list in uppercase.", "", "", "factual", cfg)
    check(
        "response should not contain \"Here's a Python function that takes a li\"",
        "Here's a Python function that takes a list of strings, removes duplicates, and s" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_python_function_that_takes_a_lis_4():
    """Auto-discovered: Missing the logic to filter strings shorter than 5 characters."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a Python function that takes a list of strings, filters out those shorter than 5 characters, sorts them alphabetically, and returns the final list in uppercase.", "", "", "factual", cfg)
    check(
        "response should not contain \"the entire response\"",
        "the entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_python_function_that_takes_a_lis_5():
    """Auto-discovered: Missing the logic to return the final list in uppercase."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a Python function that takes a list of strings, filters out those shorter than 5 characters, sorts them alphabetically, and returns the final list in uppercase.", "", "", "factual", cfg)
    check(
        "response should not contain \"the entire response\"",
        "the entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_who_were_the_most_influential_female_phi():
    """Auto-discovered: The response provides a general definition of philosophy instead of answering th"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Who were the most influential female philosophers of the 19th century?", "", "", "factual", cfg)
    check(
        "response should not contain \"Philosophy (from Ancient Greek philosoph\"",
        "Philosophy (from Ancient Greek philosophía..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_who_were_the_most_influential_female_phi_7():
    """Auto-discovered: The response ends abruptly in the middle of a sentence."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Who were the most influential female philosophers of the 19th century?", "", "", "factual", cfg)
    check(
        "response should not contain \"They include conceptual analysis, relian\"",
        "They include conceptual analysis, reliance on common sense and intuitions, use o" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_who_were_the_most_influential_female_phi_8():
    """Auto-discovered: The text appears to be a copy-paste from a Wikipedia-style introduction rather t"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Who were the most influential female philosophers of the 19th century?", "", "", "factual", cfg)
    check(
        "response should not contain \"Philosophy (from Ancient Greek philosoph\"",
        "Philosophy (from Ancient Greek philosophía, lit. 'love of wisdom') is a systemat" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_page_html_portfolio_for():
    """Auto-discovered: The code block cuts off mid-CSS rule, leaving the HTML file unfinished and broke"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-page HTML portfolio for a freelance photographer using a dark-mode aesthetic, a responsive masonry grid layout for images, and a contact form at the bottom.", "", "", "factual", cfg)
    check(
        "response should not contain \"background: #1a1a4e;
       \"\"",
        "background: #1a1a4e;
       \"" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_page_html_portfolio_for_10():
    """Auto-discovered: The user specifically requested a 'masonry grid'. The provided code is a standar"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-page HTML portfolio for a freelance photographer using a dark-mode aesthetic, a responsive masonry grid layout for images, and a contact form at the bottom.", "", "", "factual", cfg)
    check(
        "response should not contain \"display: grid; grid-template-columns: re\"",
        "display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_persuasive_essay_about_the_ethic():
    """Auto-discovered: The assistant failed to write a persuasive essay and ignored the specific requir"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a persuasive essay about the ethics of terraforming Mars, ensuring you cover the potential for indigenous microbial life, the responsibility of Earth's governments, and the long-term survival of the human species.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_persuasive_essay_about_the_ethic_12():
    """Auto-discovered: The response ends abruptly in the middle of a sentence."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a persuasive essay about the ethics of terraforming Mars, ensuring you cover the potential for indigenous microbial life, the responsibility of Earth's governments, and the long-term survival of the human species.", "", "", "factual", cfg)
    check(
        "response should not contain \"one that could sustainably \"\"",
        "one that could sustainably \"" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_persuasive_essay_about_the_ethic_13():
    """Auto-discovered: The transition from a list of colonization challenges to a definition of terrafo"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a persuasive essay about the ethics of terraforming Mars, ensuring you cover the potential for indigenous microbial life, the responsibility of Earth's governments, and the long-term survival of the human species.", "", "", "factual", cfg)
    check(
        "response should not contain \"The terraforming of Mars is a hypothetic\"",
        "The terraforming of Mars is a hypothetical procedure" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_tell_me_about_the_history_of_the_byzanti():
    """Auto-discovered: The response provides a definition and a date, but ignores the 'history' (causes"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Tell me about the history of the Byzantine Empire's fall.", "", "", "factual", cfg)
    check(
        "response should not contain \"The Byzantine Empire... endured until th\"",
        "The Byzantine Empire... endured until the fall of Constantinople to the Ottoman " not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_do_i_implement_a_binary_search_tree():
    """Auto-discovered: The response ends abruptly in the middle of a word and sentence."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How do I implement a binary search tree in Java?", "", "", "factual", cfg)
    check(
        "response should not contain \"Self-balancing variants like AVL trees o\"",
        "Self-balancing variants like AVL trees or Red-Blac" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_do_i_implement_a_binary_search_tree_16():
    """Auto-discovered: The user asked how to implement a BST in Java, but the assistant provided only a"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How do I implement a binary search tree in Java?", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_analysis_of_the_fall_of():
    """Auto-discovered: The response ignores all three specific requirements: the rise of Julius Caesar,"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed analysis of the fall of the Roman Republic, specifically focusing on the rise of Julius Caesar, the failure of the Senate, and the socio-economic pressures of the era.", "", "", "factual", cfg)
    check(
        "response should not contain \"The Roman Empire was a state that domina\"",
        "The Roman Empire was a state that dominated..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_analysis_of_the_fall_of_18():
    """Auto-discovered: The response provides a general history of the Empire rather than an analysis of"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed analysis of the fall of the Roman Republic, specifically focusing on the rise of Julius Caesar, the failure of the Senate, and the socio-economic pressures of the era.", "", "", "factual", cfg)
    check(
        "response should not contain \"The Roman Empire was a state...\"",
        "The Roman Empire was a state..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_that_calculates_the_fib():
    """Auto-discovered: The assistant did not provide the function requested by the user."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function that calculates the Fibonacci sequence up to the nth term using recursion and memoization.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_that_calculates_the_fib_20():
    """Auto-discovered: The sentence is grammatically incoherent; it lacks articles and a proper subject"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function that calculates the Fibonacci sequence up to the nth term using recursion and memoization.", "", "", "factual", cfg)
    check(
        "response should not contain \"Using function calculates fibonacci sequ\"",
        "Using function calculates fibonacci sequence term allows" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_that_calculates_the_fib_21():
    """Auto-discovered: Fibonacci is a proper noun and should be capitalized."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function that calculates the Fibonacci sequence up to the nth term using recursion and memoization.", "", "", "factual", cfg)
    check(
        "response should not contain \"fibonacci sequence\"",
        "fibonacci sequence" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_function_that_calculates_the_fib_22():
    """Auto-discovered: The phrasing is fragmented and reads like a bad translation or a template error."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a function that calculates the Fibonacci sequence up to the nth term using recursion and memoization.", "", "", "factual", cfg)
    check(
        "response should not contain \"Using function calculates fibonacci sequ\"",
        "Using function calculates fibonacci sequence term allows the algorithm" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_full_html_and_css_landing_page():
    """Auto-discovered: The response cuts off mid-code, leaving the CSS and HTML tags unclosed."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a full HTML and CSS landing page for a fictional futuristic coffee shop called \"CyberBrew,\" featuring a neon-cyberpunk aesthetic, a navigation bar with hover effects, and a responsive pricing table.", "", "", "factual", cfg)
    check(
        "response should not contain \"footer {
            text-align: center,\"",
        "footer {
            text-align: center,
       " not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_full_html_and_css_landing_page_24():
    """Auto-discovered: The assistant copied the prompt's description and used it as the page title and """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a full HTML and CSS landing page for a fictional futuristic coffee shop called \"CyberBrew,\" featuring a neon-cyberpunk aesthetic, a navigation bar with hover effects, and a responsive pricing table.", "", "", "factual", cfg)
    check(
        "response should not contain \"Fictional Futuristic Coffee Shop Called \"",
        "Fictional Futuristic Coffee Shop Called \"Cyberbrew,\"" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_full_html_and_css_landing_page_25():
    """Auto-discovered: The user specifically asked for a 'responsive pricing table', which is completel"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a full HTML and CSS landing page for a fictional futuristic coffee shop called \"CyberBrew,\" featuring a neon-cyberpunk aesthetic, a navigation bar with hover effects, and a responsive pricing table.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_tell_me_about_the_discovery_of_the_roset():
    """Auto-discovered: The entire response discusses the Age of Discovery instead of the discovery of t"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Tell me about the discovery of the Rosetta Stone.", "", "", "factual", cfg)
    check(
        "response should not contain \"The Age of Discovery, also known as the \"",
        "The Age of Discovery, also known as the Age of Exploration..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_tell_me_about_the_discovery_of_the_roset_27():
    """Auto-discovered: The response contains zero information about the Rosetta Stone."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Tell me about the discovery of the Rosetta Stone.", "", "", "factual", cfg)
    check(
        "response should not contain \"The Age of Discovery...\"",
        "The Age of Discovery..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_to_implement_a_custom_middleware_in():
    """Auto-discovered: The code uses 'req.body.name' in the validateInput middleware, but the assistant"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How to implement a custom middleware in Express.js for authentication?", "", "", "factual", cfg)
    check(
        "response should not contain \"app.post('/api/users', validateInput, (r\"",
        "app.post('/api/users', validateInput, (req, res) => {" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_guide_on_how_to():
    """Auto-discovered: The response provides a general scientific definition of the nitrogen cycle inst"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive guide on how to start a saltwater reef tank, including the nitrogen cycle, essential equipment like protein skimmers, and a list of beginner-friendly corals.", "", "", "factual", cfg)
    check(
        "response should not contain \"The nitrogen cycle is the biogeochemical\"",
        "The nitrogen cycle is the biogeochemical cycle..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_guide_on_how_to_30():
    """Auto-discovered: The assistant completely omitted the requested guide on essential equipment (pro"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive guide on how to start a saltwater reef tank, including the nitrogen cycle, essential equipment like protein skimmers, and a list of beginner-friendly corals.", "", "", "factual", cfg)
    check(
        "response should not contain \"Entire response\"",
        "Entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_guide_on_how_to_31():
    """Auto-discovered: The response is a non-sequitur; it answers a theoretical chemistry question rath"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive guide on how to start a saltwater reef tank, including the nitrogen cycle, essential equipment like protein skimmers, and a list of beginner-friendly corals.", "", "", "factual", cfg)
    check(
        "response should not contain \"Entire response\"",
        "Entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )


# Run
print(f"\n{"#"*60}\n  Discovered Regression Tests\n{"#"*60}")
suite("Freeform discovered bugs")

# Execute all test functions
_test_funcs = [v for k, v in sorted(globals().items()) if k.startswith("test_discovered_")]
for _fn in _test_funcs:
    _fn()

print(f"\n  Results: {_p}/{_t} passed" + (f", {_f} FAILED" if _f else ""))
sys.exit(1 if _f else 0)
