#!/usr/bin/env python3
"""
Discovered regression tests — auto-generated by freeform_bench.py.

These tests prevent specific mistakes from recurring.
Run: PYTHONPATH=src python tests/test_freeform_discovered.py
"""

import os, sys, re

_SRC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src")
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

from cos.nlg.pipeline import naturalize
from cos.nlg.config import NLGConfig

_t = 0; _p = 0; _f = 0
def suite(name):
    print(f"\n  Suite: {name}")
def check(n, c, d=""):
    global _t, _p, _f; _t += 1
    if c: _p += 1; print(f"    \u2713 {n}")
    else: _f += 1; print(f"    \u2717 {n}" + (f"\n        {d}" if d else ""))

def test_discovered_how_does_a_skyscraper_actually_withstand():
    """Auto-discovered: The response ignores the core question about skyscraper earthquake resistance an"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How does a skyscraper actually withstand a massive earthquake?", "", "", "factual", cfg)
    check(
        "response should not contain \"In essence, massive is an adjective rela\"",
        "In essence, massive is an adjective related to mass." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_is_the_most_mysterious_unsolved_man():
    """Auto-discovered: The response completely ignores the user's prompt about unsolved manuscripts and"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What is the most mysterious unsolved manuscript in history?", "", "", "factual", cfg)
    check(
        "response should not contain \"Simply put, problem solving is the proce\"",
        "Simply put, problem solving is the process of achieving a goal" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_is_the_most_mysterious_unsolved_man_2():
    """Auto-discovered: The response cuts off abruptly at the end."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What is the most mysterious unsolved manuscript in history?", "", "", "factual", cfg)
    check(
        "response should not contain \"but it's\"",
        "but it's" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_is_the_most_mysterious_unsolved_man_3():
    """Auto-discovered: The assistant failed to identify any mysterious manuscripts (e.g., Voynich Manus"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What is the most mysterious unsolved manuscript in history?", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_do_some_people_experience_synesthesi():
    """Auto-discovered: The response is entirely unrelated to the user's question about synesthesia."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why do some people experience synesthesia where they see colors when hearing music?", "", "", "factual", cfg)
    check(
        "response should not contain \"A manuscript was, traditionally, any doc\"",
        "A manuscript was, traditionally, any document written by hand..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_do_some_people_experience_synesthesi_5():
    """Auto-discovered: The response fails to address the user's query regarding why people see colors w"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why do some people experience synesthesia where they see colors when hearing music?", "", "", "factual", cfg)
    check(
        "response should not contain \"A manuscript was...\"",
        "A manuscript was..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_tell_me_about_the_most_isolated_inhabite():
    """Auto-discovered: The assistant failed to answer the specific question about the most isolated inh"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Tell me about the most isolated inhabited place on Earth.", "", "", "factual", cfg)
    check(
        "response should not contain \"In Canada, the designations remote, isol\"",
        "In Canada, the designations remote, isolated, outport and fly-in refer to..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_tell_me_about_the_most_isolated_inhabite_7():
    """Auto-discovered: The response is non-sequitur; it does not address the prompt's intent."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Tell me about the most isolated inhabited place on Earth.", "", "", "factual", cfg)
    check(
        "response should not contain \"In Canada, the designations remote, isol\"",
        "In Canada, the designations remote, isolated, outport and fly-in refer to a sett" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_would_actually_happen_to_a_human_bo():
    """Auto-discovered: The assistant fails to provide any information about spaghettification or event """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What would actually happen to a human body if it fell into a black hole?", "", "", "factual", cfg)
    check(
        "response should not contain \"I'm still learning about that topic.\"",
        "I'm still learning about that topic." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_would_actually_happen_to_a_human_bo_9():
    """Auto-discovered: The response uses a generic 'I don't know' template for a query that does not re"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What would actually happen to a human body if it fell into a black hole?", "", "", "factual", cfg)
    check(
        "response should not contain \"Could you share more details about what \"",
        "Could you share more details about what you're looking for?" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_did_the_concept_of_time_evolve_from():
    """Auto-discovered: The assistant failed to provide any information regarding the evolution of timek"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How did the concept of \"time\" evolve from sundials to atomic clocks?", "", "", "factual", cfg)
    check(
        "response should not contain \"I'm still learning about that topic.\"",
        "I'm still learning about that topic." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_did_the_concept_of_time_evolve_from_11():
    """Auto-discovered: This is a generic fallback response used when the AI cannot answer, rather than """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How did the concept of \"time\" evolve from sundials to atomic clocks?", "", "", "factual", cfg)
    check(
        "response should not contain \"Could you share more details about what \"",
        "Could you share more details about what you're looking for?" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_is_it_that_some_melodies_evoke_such():
    """Auto-discovered: Missing verb and incorrect syntax; it repeats the prompt instead of forming a se"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why is it that some melodies evoke such strong emotions even if we've never heard them before?", "", "", "factual", cfg)
    check(
        "response should not contain \"The reason it that some melodies evoke s\"",
        "The reason it that some melodies evoke such strong emotions" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_is_it_that_some_melodies_evoke_such_13():
    """Auto-discovered: The sentence structure is nonsensical and grammatically collapsed."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why is it that some melodies evoke such strong emotions even if we've never heard them before?", "", "", "factual", cfg)
    check(
        "response should not contain \"works the way it does is largely due to\"",
        "works the way it does is largely due to" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_is_it_that_some_melodies_evoke_such_14():
    """Auto-discovered: The assistant verbatim repeats the user's question as a subject, creating a circ"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why is it that some melodies evoke such strong emotions even if we've never heard them before?", "", "", "factual", cfg)
    check(
        "response should not contain \"it that some melodies evoke such strong \"",
        "it that some melodies evoke such strong emotions even if we've never heard them " not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_is_it_that_some_melodies_evoke_such_15():
    """Auto-discovered: The response treats emotional musical response as a conscious 'tool' developed b"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why is it that some melodies evoke such strong emotions even if we've never heard them before?", "", "", "factual", cfg)
    check(
        "response should not contain \"highly optimized tool for communication \"",
        "highly optimized tool for communication that has been refined over centuries" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_is_it_that_some_melodies_evoke_such_16():
    """Auto-discovered: The entire second sentence is a syntactic disaster that fails to convey a clear """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why is it that some melodies evoke such strong emotions even if we've never heard them before?", "", "", "factual", cfg)
    check(
        "response should not contain \"The reason it that... works the way it d\"",
        "The reason it that... works the way it does is" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_are_the_most_effective_ways_to_redu():
    """Auto-discovered: The response provides a definition of a word instead of answering the user's req"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What are the most effective ways to reduce plastic waste in a typical household?", "", "", "factual", cfg)
    check(
        "response should not contain \"Effectiveness or effectivity is the capa\"",
        "Effectiveness or effectivity is the capability..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_are_the_most_effective_ways_to_redu_18():
    """Auto-discovered: Incorrect passive construction; 'has' should be 'is' or 'has been'."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What are the most effective ways to reduce plastic waste in a typical household?", "", "", "factual", cfg)
    check(
        "response should not contain \"When something has deemed effective\"",
        "When something has deemed effective" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_does_the_gut_microbiome_actually_inf():
    """Auto-discovered: The assistant refuses to answer a general knowledge question about the gut-brain"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How does the gut microbiome actually influence our mental health and mood?", "", "", "factual", cfg)
    check(
        "response should not contain \"That's outside what I currently know wel\"",
        "That's outside what I currently know well enough to explain confidently." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_does_the_gut_microbiome_actually_inf_20():
    """Auto-discovered: The phrasing sounds like a canned refusal or a restrictive system prompt rather """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How does the gut microbiome actually influence our mental health and mood?", "", "", "factual", cfg)
    check(
        "response should not contain \"That's outside what I currently know wel\"",
        "That's outside what I currently know well enough to explain confidently." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_what_is_the_philosophy_behind_the_ship_o():
    """Auto-discovered: The response defines the paradox but ignores the 'philosophy behind' it (e.g., p"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("What is the philosophy behind the \"Ship of Theseus\" paradox?", "", "", "factual", cfg)
    check(
        "response should not contain \"The Ship of Theseus... is a paradox and \"",
        "The Ship of Theseus... is a paradox and common thought experiment about whether " not in response,
        f"Found problematic text in response: {response[:150]}"
    )


# Run
print(f"\n{"#"*60}\n  Discovered Regression Tests\n{"#"*60}")
suite("Freeform discovered bugs")

# Execute all test functions
_test_funcs = [v for k, v in sorted(globals().items()) if k.startswith("test_discovered_")]
for _fn in _test_funcs:
    _fn()

print(f"\n  Results: {_p}/{_t} passed" + (f", {_f} FAILED" if _f else ""))
sys.exit(1 if _f else 0)
