#!/usr/bin/env python3
"""
Discovered regression tests — auto-generated by freeform_bench.py.

These tests prevent specific mistakes from recurring.
Run: PYTHONPATH=src python tests/test_freeform_discovered.py
"""

import os, sys, re

_SRC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src")
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

from cos.nlg.pipeline import naturalize
from cos.nlg.config import NLGConfig

_t = 0; _p = 0; _f = 0
def suite(name):
    print(f"\n  Suite: {name}")
def check(n, c, d=""):
    global _t, _p, _f; _t += 1
    if c: _p += 1; print(f"    \u2713 {n}")
    else: _f += 1; print(f"    \u2717 {n}" + (f"\n        {d}" if d else ""))

def test_discovered_why_do_we_dream_and_what_is_the_leading():
    """Auto-discovered: The assistant failed to explain why we dream or mention any scientific theories """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why do we dream and what is the leading scientific theory on why it happens?", "", "", "factual", cfg)
    check(
        "response should not contain \"entire response\"",
        "entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_me_a_detailed_essay_on_the_fall_of():
    """Auto-discovered: The assistant provided a summary/list of facts rather than a structured essay wi"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write me a detailed essay on the fall of the Roman Empire, making sure to analyze both the internal political decay and the external pressures from barbarian tribes.", "", "", "factual", cfg)
    check(
        "response should not contain \"Write me a detailed essay\"",
        "Write me a detailed essay" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_me_a_detailed_essay_on_the_fall_of_2():
    """Auto-discovered: The response cuts off abruptly at the end of the final sentence."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write me a detailed essay on the fall of the Roman Empire, making sure to analyze both the internal political decay and the external pressures from barbarian tribes.", "", "", "factual", cfg)
    check(
        "response should not contain \"and the efficiency of the civil administ\"",
        "and the efficiency of the civil administrati" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_me_a_detailed_essay_on_the_fall_of_3():
    """Auto-discovered: The text repeats the definition of the event in a way that sounds like a Wikiped"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write me a detailed essay on the fall of the Roman Empire, making sure to analyze both the internal political decay and the external pressures from barbarian tribes.", "", "", "factual", cfg)
    check(
        "response should not contain \"The fall of the Western Roman Empire, al\"",
        "The fall of the Western Roman Empire, also called the fall of the Roman Empire" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_me_a_detailed_essay_on_the_fall_of_4():
    """Auto-discovered: The transition from a narrative introduction to a list-like structure is jarring"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write me a detailed essay on the fall of the Roman Empire, making sure to analyze both the internal political decay and the external pressures from barbarian tribes.", "", "", "factual", cfg)
    check(
        "response should not contain \"Key causes included: the Crisis of the T\"",
        "Key causes included: the Crisis of the Third Century" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_python_function_that_takes_a_lis():
    """Auto-discovered: The assistant ignored the user's request for string filtering and instead wrote """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a Python function that takes a list of strings, filters out those shorter than five characters, and returns the remaining strings sorted alphabetically.", "", "", "factual", cfg)
    check(
        "response should not contain \"Here's a Python function that takes a li\"",
        "Here's a Python function that takes a list of integers, removes duplicates" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_python_function_that_takes_a_lis_6():
    """Auto-discovered: The response is missing the logic to filter strings by length (>= 5) and the log"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a Python function that takes a list of strings, filters out those shorter than five characters, and returns the remaining strings sorted alphabetically.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_detailed_explanation_of_how_qu():
    """Auto-discovered: The assistant has inserted the user's prompt instructions directly into the sent"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a detailed explanation of how quantum entanglement works, including the EPR paradox, the concept of superposition, and how it differs from classical correlation.", "", "", "factual", cfg)
    check(
        "response should not contain \"Let me provide a thorough explanation of\"",
        "Let me provide a thorough explanation of give detailed explanation quantum entan" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_detailed_explanation_of_how_qu_8():
    """Auto-discovered: The section contains zero actual information about quantum physics, superpositio"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a detailed explanation of how quantum entanglement works, including the EPR paradox, the concept of superposition, and how it differs from classical correlation.", "", "", "factual", cfg)
    check(
        "response should not contain \"The Fundamentals\"",
        "The Fundamentals" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_detailed_explanation_of_how_qu_9():
    """Auto-discovered: The section describes 'interconnected processes' without naming or explaining an"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a detailed explanation of how quantum entanglement works, including the EPR paradox, the concept of superposition, and how it differs from classical correlation.", "", "", "factual", cfg)
    check(
        "response should not contain \"How It Works\"",
        "How It Works" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_detailed_explanation_of_how_qu_10():
    """Auto-discovered: The assistant completely ignored the specific requests for the EPR paradox, supe"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a detailed explanation of how quantum entanglement works, including the EPR paradox, the concept of superposition, and how it differs from classical correlation.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_detailed_explanation_of_how_qu_11():
    """Auto-discovered: Incorrect use of the prompt as a subject; grammatically incoherent."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a detailed explanation of how quantum entanglement works, including the EPR paradox, the concept of superposition, and how it differs from classical correlation.", "", "", "factual", cfg)
    check(
        "response should not contain \"What Is give detailed explanation quantu\"",
        "What Is give detailed explanation quantum entanglement?" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_detailed_explanation_of_how_qu_12():
    """Auto-discovered: The response treats the instruction 'give detailed explanation' as part of the n"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a detailed explanation of how quantum entanglement works, including the EPR paradox, the concept of superposition, and how it differs from classical correlation.", "", "", "factual", cfg)
    check(
        "response should not contain \"give detailed explanation quantum entang\"",
        "give detailed explanation quantum entanglement is a multifaceted subject" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_did_the_invention_of_the_printing_pr():
    """Auto-discovered: The response provides a general overview of the printing press's impact rather t"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How did the invention of the printing press specifically change the religious landscape of Europe?", "", "", "factual", cfg)
    check(
        "response should not contain \"The printing press had an enormous impac\"",
        "The printing press had an enormous impact on European and world history." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_page_html_portfolio_for():
    """Auto-discovered: The code block ends abruptly mid-CSS rule, leaving the HTML file unfinished and """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-page HTML portfolio for a freelance photographer using a dark-mode aesthetic, a responsive masonry grid layout for images, and a contact form at the bottom.", "", "", "factual", cfg)
    check(
        "response should not contain \"background: #1a1a4e;
       \"\"",
        "background: #1a1a4e;
       \"" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_single_page_html_portfolio_for_15():
    """Auto-discovered: The user specifically requested a 'masonry grid layout'. The assistant provided """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a single-page HTML portfolio for a freelance photographer using a dark-mode aesthetic, a responsive masonry grid layout for images, and a contact form at the bottom.", "", "", "factual", cfg)
    check(
        "response should not contain \"grid-template-columns: repeat(auto-fit, \"",
        "grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_who_is_considered_the_father_of_conceptu():
    """Auto-discovered: The assistant misinterpreted the metaphorical use of 'father of' (meaning founde"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Who is considered the father of conceptual art and why?", "", "", "factual", cfg)
    check(
        "response should not contain \"A father, dad, or daddy, is the male par\"",
        "A father, dad, or daddy, is the male parent of a child." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_who_is_considered_the_father_of_conceptu_17():
    """Auto-discovered: The response contains zero information regarding conceptual art, the artists inv"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Who is considered the father of conceptual art and why?", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_who_is_considered_the_father_of_conceptu_18():
    """Auto-discovered: The response cuts off abruptly at the end."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Who is considered the father of conceptual art and why?", "", "", "factual", cfg)
    check(
        "response should not contain \"Positive parenting is par\"",
        "Positive parenting is par" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_to_implement_a_custom_hook_in_react():
    """Auto-discovered: The assistant provided a solution for data fetching instead of window resizing, """
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How to implement a custom hook in React to handle window resizing?", "", "", "factual", cfg)
    check(
        "response should not contain \"For data fetching, a custom hook typical\"",
        "For data fetching, a custom hook typically manages loading..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_to_implement_a_custom_hook_in_react_20():
    """Auto-discovered: The response cuts off abruptly at the end."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How to implement a custom hook in React to handle window resizing?", "", "", "factual", cfg)
    check(
        "response should not contain \"always handle the cleanup function in `u\"",
        "always handle the cleanup function in `useEffect` to abo" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_how_to_implement_a_custom_hook_in_react_21():
    """Auto-discovered: The response contains no information regarding window resizing, event listeners,"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("How to implement a custom hook in React to handle window resizing?", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_comparison_of_stoicism():
    """Auto-discovered: The assistant failed to address the specific prompts: differing views on pleasur"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed comparison of Stoicism and Epicureanism, focusing on their differing views on pleasure, the role of emotion in a virtuous life, and their respective approaches to handling grief.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_comparison_of_stoicism_23():
    """Auto-discovered: Complete non-sequitur; the assistant suddenly switches from philosophy to defini"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed comparison of Stoicism and Epicureanism, focusing on their differing views on pleasure, the role of emotion in a virtuous life, and their respective approaches to handling grief.", "", "", "factual", cfg)
    check(
        "response should not contain \"Writing is the act of creating a persist\"",
        "Writing is the act of creating a persistent..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_detailed_comparison_of_stoicism_24():
    """Auto-discovered: The response cuts off mid-word at the very end."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a detailed comparison of Stoicism and Epicureanism, focusing on their differing views on pleasure, the role of emotion in a virtuous life, and their respective approaches to handling grief.", "", "", "factual", cfg)
    check(
        "response should not contain \"digitall\"",
        "digitall" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_responsive_html_landing_page_fo():
    """Auto-discovered: The code block ends abruptly, leaving the CSS media query and the entire HTML bo"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a responsive HTML landing page for a fictional futuristic travel agency with a neon-cyberpunk aesthetic, a three-column feature section, and an embedded Google Maps iframe.", "", "", "factual", cfg)
    check(
        "response should not contain \"@media (max-width: 768px) {\"",
        "@media (max-width: 768px) {" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_responsive_html_landing_page_fo_26():
    """Auto-discovered: The assistant failed to include the embedded Google Maps iframe requested by the"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a responsive HTML landing page for a fictional futuristic travel agency with a neon-cyberpunk aesthetic, a three-column feature section, and an embedded Google Maps iframe.", "", "", "factual", cfg)
    check(
        "response should not contain \"entire response\"",
        "entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_create_a_responsive_html_landing_page_fo_27():
    """Auto-discovered: The assistant failed to provide the actual HTML content for the three-column fea"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Create a responsive HTML landing page for a fictional futuristic travel agency with a neon-cyberpunk aesthetic, a three-column feature section, and an embedded Google Maps iframe.", "", "", "factual", cfg)
    check(
        "response should not contain \"entire response\"",
        "entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_why_is_the_ocean_mostly_unexplored_compa():
    """Auto-discovered: The response cuts off mid-sentence at the very end."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Why is the ocean mostly unexplored compared to outer space?", "", "", "factual", cfg)
    check(
        "response should not contain \"but it will likely\"",
        "but it will likely" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_javascript_function_that_validat():
    """Auto-discovered: The assistant failed to provide the JavaScript function requested by the user."""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a JavaScript function that validates an email address, checks if the domain is on a blacklist, and then formats the string to be lowercase.", "", "", "factual", cfg)
    check(
        "response should not contain \"The entire response\"",
        "The entire response" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_javascript_function_that_validat_30():
    """Auto-discovered: The response uses a generic filler template that repeats the user's keywords wit"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a JavaScript function that validates an email address, checks if the domain is on a blacklist, and then formats the string to be lowercase.", "", "", "factual", cfg)
    check(
        "response should not contain \"Great, let me expand on javascript funct\"",
        "Great, let me expand on javascript function validates email address, further!" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_javascript_function_that_validat_31():
    """Auto-discovered: Incorrect phrasing and punctuation; it treats a descriptive phrase as a noun and"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a JavaScript function that validates an email address, checks if the domain is on a blacklist, and then formats the string to be lowercase.", "", "", "factual", cfg)
    check(
        "response should not contain \"javascript function validates email addr\"",
        "javascript function validates email address," not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_write_a_javascript_function_that_validat_32():
    """Auto-discovered: The exact phrase is repeated in every single paragraph, creating a robotic and u"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Write a JavaScript function that validates an email address, checks if the domain is on a blacklist, and then formats the string to be lowercase.", "", "", "factual", cfg)
    check(
        "response should not contain \"javascript function validates email addr\"",
        "javascript function validates email address" not in response,
        f"Found problematic text in response: {response[:150]}"
    )

def test_discovered_give_me_a_comprehensive_breakdown_of_the():
    """Auto-discovered: The user asked for a 'comprehensive breakdown' including specific roles of Sea P"""
    cfg = NLGConfig(style="friendly", verbosity=0.5, temperature=0.0)
    response = naturalize("Give me a comprehensive breakdown of the Bronze Age Collapse, including the role of the \"Sea Peoples,\" the impact of climate change, and how the disruption of trade networks led to the fall of multiple civilizations.", "", "", "factual", cfg)
    check(
        "response should not contain \"The Bronze Age collapse was a period...\"",
        "The Bronze Age collapse was a period..." not in response,
        f"Found problematic text in response: {response[:150]}"
    )


# Run
print(f"\n{"#"*60}\n  Discovered Regression Tests\n{"#"*60}")
suite("Freeform discovered bugs")

# Execute all test functions
_test_funcs = [v for k, v in sorted(globals().items()) if k.startswith("test_discovered_")]
for _fn in _test_funcs:
    _fn()

print(f"\n  Results: {_p}/{_t} passed" + (f", {_f} FAILED" if _f else ""))
sys.exit(1 if _f else 0)
