"""Expand the aliases JSON file with hundreds of new entries."""
import json
import sys
import os

# Change to project root
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Read existing aliases
with open('data/aliases.json', 'r') as f:
    content = f.read()

# Fix broken content
content = content.replace('"d [L448]\\n 00e9j [L449]\\n  00e0 vu [L449]', '')

data = json.loads(content)
print(f'Existing entries: {len(data)}')

# Remove broken key
if 'd' in data:
    del data['d']

# Add new aliases
new_aliases = {
    # Science topics
    'what would happen if all plants': 'Atmosphere of Earth',
    'plants disappeared from earth': 'Atmosphere of Earth',
    'without plants earth': 'Atmosphere of Earth',
    'all the plants disappeared': 'Atmosphere of Earth',
    'twin paradox': 'Twin paradox',
    'special relativity': 'Special relativity',
    'general relativity': 'General relativity',
    'electromagnetic spectrum': 'Electromagnetic spectrum',
    'how do wings generate lift': 'Lift (force)',
    'airplane wings generate lift': 'Lift (force)',
    'why is the sky blue': 'Diffuse sky radiation',
    'sky appears blue': 'Diffuse sky radiation',
    'ocean appears blue': 'Ocean color',
    'why is the ocean blue': 'Ocean color',
    'how do birds fly': 'Bird flight',
    'flight mechanism birds': 'Bird flight',
    'what causes lightning': 'Lightning',
    'how lightning forms': 'Lightning',
    'difference weather climate': 'Climate',
    'how do seasons work': 'Season',
    'why do we have seasons': 'Season',
    'ozone layer depletion': 'Ozone depletion',
    'ozone layer function': 'Ozone layer',
    'how do vaccines work': 'Vaccine',
    'vaccines mechanism': 'Vaccine',
    'mrna vaccine technology': 'mRNA vaccine',
    'antibiotics kill bacteria': 'Antibiotic',
    'how antibiotics work': 'Antibiotic',
    'antibiotic resistance': 'Antimicrobial resistance',
    'how does evolution work': 'Evolution',
    'natural selection explain': 'Natural selection',
    'dna replication': 'DNA replication',
    'protein synthesis': 'Protein synthesis',
    'how proteins are made': 'Protein synthesis',
    'cells divide mitosis': 'Mitosis',
    'mitosis vs meiosis': 'Meiosis',
    'difference mitosis meiosis': 'Meiosis',
    'how do muscles grow': 'Muscle hypertrophy',
    'muscle growth mechanism': 'Muscle hypertrophy',
    'how does memory work': 'Memory',
    'human memory formation': 'Memory',
    'how memories formed': 'Memory',
    'rem sleep function': 'Rapid eye movement sleep',
    'why we need sleep': 'Sleep',
    'circadian rhythm': 'Circadian rhythm',
    'internal body clock': 'Circadian rhythm',
    'how do eyes see color': 'Color vision',
    'color vision mechanism': 'Color vision',
    'why do we yawn': 'Yawn',
    'why we yawn when tired': 'Yawn',
    'how does anesthesia work': 'Anesthesia',
    'general anesthesia mechanism': 'Anesthesia',
    'how placebo works': 'Placebo',
    'how does chemotherapy work': 'Chemotherapy',
    'how does dialysis work': 'Dialysis',
    'kidney dialysis process': 'Dialysis',
    'how does an mri work': 'Magnetic resonance imaging',
    'mri scan mechanism': 'Magnetic resonance imaging',
    'how ultrasound works': 'Medical ultrasound',
    'ultrasound imaging': 'Medical ultrasound',
    'how do x rays work': 'X-ray',
    'x ray imaging': 'X-ray',
    'how does radar work': 'Radar',
    'radar technology': 'Radar',
    'how does lidar work': 'Lidar',
    'lidar technology': 'Lidar',
    'how does sonar work': 'Sonar',
    'sonar technology': 'Sonar',
    'how does wifi work': 'Wi-Fi',
    'wireless internet': 'Wi-Fi',
    'how does bluetooth work': 'Bluetooth',
    'bluetooth technology': 'Bluetooth',
    'how does gps work': 'Global Positioning System',
    'gps satellite navigation': 'Global Positioning System',
    'how does a compass work': 'Compass',
    'magnetic compass': 'Compass',
    'how does a battery work': 'Electric battery',
    'battery chemistry': 'Electric battery',
    'lithium ion battery': 'Lithium-ion battery',
    'how does solar panel work': 'Solar panel',
    'solar cell technology': 'Solar panel',
    'how does wind turbine work': 'Wind turbine',
    'wind energy': 'Wind turbine',
    'how does nuclear power work': 'Nuclear power',
    'nuclear fission reactor': 'Nuclear power',
    'how does a microwave work': 'Microwave oven',
    'how does refrigerator work': 'Refrigerator',
    'refrigeration cycle': 'Refrigerator',
    'how does air conditioning work': 'Air conditioning',
    'ac cooling principle': 'Air conditioning',
    'how does a toilet work': 'Toilet',
    'how does a lock work': 'Lock and key',
    'pin tumbler lock': 'Lock and key',
    'how does a camera work': 'Camera',
    'camera mechanism': 'Camera',
    'digital camera sensor': 'Image sensor',
    'how does 3d printing work': '3D printing',
    'additive manufacturing': '3D printing',
    'how does a laser work': 'Laser',
    'laser technology': 'Laser',
    'how does fiber optics work': 'Fiber-optic communication',
    'fiber optic internet': 'Fiber-optic communication',
    'how does a transistor work': 'Transistor',
    'transistor function': 'Transistor',
    'how does a microphone work': 'Microphone',
    'microphone types': 'Microphone',
    'how does a speaker work': 'Loudspeaker',
    'speaker driver': 'Loudspeaker',
    'how does a vacuum cleaner work': 'Vacuum cleaner',
    'how does a washing machine work': 'Washing machine',
    'how does an engine work': 'Internal combustion engine',
    'four stroke engine': 'Internal combustion engine',
    'diesel engine vs gasoline': 'Diesel engine',
    'how does a turbine work': 'Turbine',
    'gas turbine': 'Turbine',
    'how does a sailboat work': 'Sailboat',
    'sailing principles': 'Sailboat',
    'how does a submarine work': 'Submarine',
    'submarine buoyancy': 'Submarine',
    'how does a helicopter work': 'Helicopter',
    'helicopter flight': 'Helicopter',
    'how does a hovercraft work': 'Hovercraft',
    'hovercraft principle': 'Hovercraft',
    # Geography & places
    'city with the most unique': 'Unique architecture',
    'most unique city architecture': 'Unique architecture',
    'most unusual architecture city': 'Unique architecture',
    'city famous architecture unusual': 'Unique architecture',
    'city known unique architecture': 'Unique architecture',
    'mars sky color': 'Mars',
    'color of mars sky': 'Atmosphere of Mars',
    'mars atmosphere color': 'Atmosphere of Mars',
    'what color is mars sky': 'Atmosphere of Mars',
    'driving age different countries': 'Driving age',
    'why driving ages differ': 'Driving age',
    'youngest driving age world': 'Driving age',
    'largest desert in the world': 'List of deserts by area',
    'biggest desert earth': 'List of deserts by area',
    'deepest point ocean': 'Mariana Trench',
    'mariana trench depth': 'Mariana Trench',
    'deepest part of the ocean': 'Mariana Trench',
    'tallest mountain world': 'Mount Everest',
    'largest mountain earth': 'Mount Everest',
    'longest river world': 'List of rivers by length',
    'largest lake world': 'List of lakes by area',
    'biggest lake': 'List of lakes by area',
    'largest ocean': 'Pacific Ocean',
    'biggest ocean earth': 'Pacific Ocean',
    'smallest country world': 'Vatican City',
    'largest country world': 'Russia',
    'most populous country': 'List of countries by population',
    'smallest country earth': 'Vatican City',
    'coldest place earth': 'List of coldest places on Earth',
    'hottest place earth': 'List of hottest places on Earth',
    'driest place earth': 'Atacama Desert',
    'wettest place earth': 'Mawsynram',
    'most mountainous country': 'List of countries by average elevation',
    'country with most islands': 'List of island countries',
    'city with most canals': 'Venice',
    'city with most skyscrapers': 'List of cities with the most skyscrapers',
    # History
    'what caused the fall of rome': 'Fall of the Western Roman Empire',
    'primary reason rome fell': 'Fall of the Western Roman Empire',
    'roman empire actually fall': 'Fall of the Western Roman Empire',
    'what caused world war 1': 'World War I',
    'what started world war 1': 'World War I',
    'immediate cause ww1': 'World War I',
    'what caused world war 2': 'World War II',
    'what started world war 2': 'World War II',
    'cold war start': 'Cold War',
    'what caused cold war': 'Cold War',
    'first civilization in the world': 'Cradle of civilization',
    'oldest known civilization': 'Cradle of civilization',
    'first writing system': 'History of writing',
    'oldest writing system': 'Cuneiform',
    'invention of the wheel': 'Wheel',
    'who invented the wheel': 'Wheel',
    'invention of agriculture': 'History of agriculture',
    'neolithic revolution': 'Neolithic Revolution',
    'industrial revolution inventions': 'Industrial Revolution',
    'most important invention human history': 'List of inventions',
    'greatest invention of all time': 'List of inventions',
    'lost city of atlantis': 'Atlantis',
    'atlantis real location': 'Atlantis',
    'myth of atlantis': 'Atlantis',
    'were pyramids built': 'Egyptian pyramid construction techniques',
    'how pyramids built': 'Egyptian pyramid construction techniques',
    'pyramid construction methods': 'Egyptian pyramid construction techniques',
    # Psychology & Mind
    'why we dream at night': 'Dream',
    'purpose of dreaming': 'Dream',
    'theories of why we dream': 'Dream',
    'why is it that we dream': 'Dream',
    'dream in stories': 'Dream',
    'why dreams are stories': 'Dream',
    'why does time speed up': 'Time perception',
    'time flies when': 'Time perception',
    'why time goes faster': 'Time perception',
    'time seems to go faster': 'Time perception',
    'why does time feel faster': 'Time perception',
    'why time passes quicker': 'Time perception',
    'songs trigger vivid memories': 'Music-evoked autobiographical memory',
    'music brings back memories': 'Music-evoked autobiographical memory',
    'song reminds me of': 'Music-evoked autobiographical memory',
    'why music triggers memories': 'Music-evoked autobiographical memory',
    'music and memory connection': 'Music-evoked autobiographical memory',
    'why certain songs trigger': 'Music-evoked autobiographical memory',
    'why do songs trigger': 'Music-evoked autobiographical memory',
    'why can i remember songs': 'Music-evoked autobiographical memory',
    'why is music so memorable': 'Music-evoked autobiographical memory',
    'nostalgia triggered music': 'Nostalgia',
    'why music makes us emotional': 'Music and emotion',
    'do animals dream': 'Dream',
    'do dogs dream': 'Dream',
    'do cats dream': 'Dream',
    'why do we forget dreams': 'Dream',
    'why we forget dreams quickly': 'Dream',
    'what causes lucid dreaming': 'Lucid dream',
    'lucid dreaming technique': 'Lucid dream',
    'how to lucid dream': 'Lucid dream',
    'why do we blush': 'Blushing',
    'blushing mechanism': 'Blushing',
    'why humans blush': 'Blushing',
    'why do we cry': 'Crying',
    'emotional tears purpose': 'Crying',
    'why do we laugh': 'Laughter',
    'what makes us laugh': 'Laughter',
    'why do we hiccup': 'Hiccup',
    'what causes hiccups': 'Hiccup',
    'why do we have goosebumps': 'Goose bumps',
    'goosebumps purpose': 'Goose bumps',
    'why do we sneeze': 'Sneeze',
    'sneeze reflex': 'Sneeze',
    'why do we have appendix': 'Appendix (anatomy)',
    'appendix function': 'Appendix (anatomy)',
    'why do we have wisdom teeth': 'Wisdom tooth',
    'wisdom teeth purpose': 'Wisdom tooth',
    'why do we have eyebrows': 'Eyebrow',
    'purpose of eyebrows': 'Eyebrow',
    'why do we have fingerprints': 'Fingerprint',
    'purpose of fingerprints': 'Fingerprint',
    'why do we have belly buttons': 'Navel',
    'belly button purpose': 'Navel',
    'why do humans have tailbones': 'Coccyx',
    'tailbone purpose': 'Coccyx',
    'why do we have different blood types': 'Blood type',
    'blood type differences': 'Blood type',
    'why do we have allergies': 'Allergy',
    'allergic reaction mechanism': 'Allergy',
    'why do we get fevers': 'Fever',
    'fever function': 'Fever',
    'why we get sick in winter': 'Common cold',
    'why do we dream in color': 'Dream',
    'do we dream in color': 'Dream',
    'why do we have nightmares': 'Nightmare',
    'purpose of nightmares': 'Nightmare',
    'what causes deja vu': 'Deja vu',
    'deja vu explanation': 'Deja vu',
    'scientific explanation deja vu': 'Deja vu',
    # Philosophy
    'philosophical argument nothing': 'Nothing',
    'why is there something': 'Nothing',
    'why is there something rather than': 'Nothing',
    'why there is something': 'Nothing',
    'something rather than nothing': 'Existence',
    'why does anything exist': 'Existence',
    'what is the meaning of life': 'Meaning of life',
    'meaning of life philosophy': 'Meaning of life',
    'purpose of existence': 'Meaning of life',
    'do we have free will': 'Free will',
    'free will debate': 'Free will',
    'philosophical argument free will': 'Free will',
    'what is consciousness': 'Consciousness',
    'nature of consciousness': 'Consciousness',
    'hard problem of consciousness': 'Hard problem of consciousness',
    'mind body problem': 'Mind-body problem',
    'philosophical zombie': 'Philosophical zombie',
    'trolley problem': 'Trolley problem',
    'trolley problem philosophy': 'Trolley problem',
    'if a tree falls in forest': 'If a tree falls in a forest',
    'tree falls forest make sound': 'If a tree falls in a forest',
    'incompleteness theorem': "Godel's incompleteness theorems",
    'axiom of choice': 'Axiom of choice',
    # Language & Linguistics
    'why languages have grammatical gender': 'Grammatical gender',
    'languages gender nouns': 'Grammatical gender',
    'why does english not have gender': 'Grammatical gender',
    'how many languages world': 'List of languages by number of native speakers',
    'most spoken language': 'List of languages by number of native speakers',
    'oldest language still spoken': 'List of languages by first written account',
    'most difficult language learn': 'Language difficulty',
    'hardest language to learn': 'Language difficulty',
    'easiest language to learn': 'Language difficulty',
    'origins of human language': 'Origin of language',
    'how did language evolve': 'Origin of language',
    'when was language invented': 'Origin of language',
    # Arts & Culture
    'why mona lisa so famous': 'Mona Lisa',
    'mona lisa painting significance': 'Mona Lisa',
    'starving artist myth': 'Starving artist',
    'why artists struggle financially': 'Starving artist',
    'what makes art valuable': 'Art valuation',
    'most expensive painting': 'List of most expensive paintings',
    'how art forgeries detected': 'Art forgery',
    'famous art forgeries': 'Art forgery',
    'most influential musicians 20th': 'List of 20th-century musicians',
    'why some music makes us cry': 'Music and emotion',
    'sad music enjoyable': 'Music and emotion',
    'why sad music feels good': 'Music and emotion',
    'why songs get stuck': 'Earworm',
    'musical earworm': 'Earworm',
    'why do songs get stuck in head': 'Earworm',
    'perfect pitch talent': 'Perfect pitch',
    'can perfect pitch learned': 'Perfect pitch',
    'what is tone deafness': 'Tone deafness',
    'amusia': 'Tone deafness',
    'why cant i sing': 'Tone deafness',
    # Technology
    'how the internet works': 'Internet',
    'how does the internet work': 'Internet',
    'how data travels internet': 'Internet',
    'how do search engines work': 'Search engine',
    'google search algorithm': 'Search engine',
    'how does google search': 'Search engine',
    'how does encryption work': 'Encryption',
    'public key encryption': 'Public-key cryptography',
    'how ssl tls works': 'Transport Layer Security',
    'https secure': 'HTTPS',
    'how does a vpn work': 'Virtual private network',
    'vpn encryption': 'Virtual private network',
    'how does tor work': 'Tor (network)',
    'tor browser anonymity': 'Tor (network)',
    'how does dns work': 'Domain Name System',
    'dns resolution': 'Domain Name System',
    'how does email work': 'Email',
    'smtp protocol': 'Email',
    'how does a firewall work': 'Firewall (computing)',
    'firewall network security': 'Firewall (computing)',
    'how do cookies work': 'HTTP cookie',
    'browser cookies': 'HTTP cookie',
    'how does a proxy work': 'Proxy server',
    'proxy server': 'Proxy server',
    'how does a compiler work': 'Compiler',
    'compiler vs interpreter': 'Compiler',
    'difference compiler interpreter': 'Compiler',
    'jit compilation': 'Just-in-time compilation',
    'how does garbage collection work': 'Garbage collection (computer science)',
    'how does a database work': 'Database',
    'relational database': 'Relational database',
    'sql vs nosql': 'NoSQL',
    'difference sql nosql': 'NoSQL',
    'how does an operating system work': 'Operating system',
    'os kernel': 'Operating system',
    'how does virtualization work': 'Virtualization',
    'hypervisor': 'Virtualization',
    'how does docker work': 'Docker (software)',
    'container vs vm': 'Docker (software)',
    'how does kubernetes work': 'Kubernetes',
    'container orchestration': 'Kubernetes',
    'how does git work': 'Git',
    'version control git': 'Git',
    'how does a blockchain work': 'Blockchain',
    'blockchain explained simply': 'Blockchain',
    # Common open-ended questions
    'why do we exist': 'Existence',
    'are we alone universe': 'Extraterrestrial life',
    'is there life on other planets': 'Extraterrestrial life',
    'what happens after death': 'Afterlife',
    'near death experience': 'Near-death experience',
    'do aliens exist': 'Extraterrestrial life',
    'alien life evidence': 'Extraterrestrial life',
    'why is water important': 'Water',
    'unique properties of water': 'Properties of water',
    'why water essential life': 'Properties of water',
    'what is the universe made of': 'Universe',
    'composition of universe': 'Universe',
    'how big is the universe': 'Universe',
    'size of observable universe': 'Observable universe',
    'age of the universe': 'Age of the universe',
    'how old is universe': 'Age of the universe',
    'how was the universe created': 'Big Bang',
    'big bang theory': 'Big Bang',
    'what came before big bang': 'Big Bang',
    'how solar system formed': 'Formation and evolution of the Solar System',
    'origin of the solar system': 'Formation and evolution of the Solar System',
    'how was earth formed': 'History of Earth',
    'formation of earth': 'History of Earth',
    'how did life begin': 'Abiogenesis',
    'origin of life on earth': 'Abiogenesis',
    'first life on earth': 'Abiogenesis',
    'how did humans evolve': 'Human evolution',
    'human evolution timeline': 'Human evolution',
    'evolution of humans': 'Human evolution',
    'where did humans come from': 'Human evolution',
    'what will future be like': 'Future',
    'singularity when': 'Technological singularity',
    'technological singularity': 'Technological singularity',
    'can computers think': 'Artificial intelligence',
    'turing test': 'Turing test',
    'does ai have consciousness': 'AI consciousness',
}

# Remove any existing keys that conflict
for k in list(new_aliases.keys()):
    if k in data:
        print(f'  Duplicate: {k}')

# Add new aliases
data.update(new_aliases)
print(f'Total entries now: {len(data)}')

# Fix the deja vu key issues
if 'd' in data:
    del data['d']

# Write back
with open('data/aliases.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print('Done!')
