#!/usr/bin/env python3
"""Round 10a: add go/rust/java/c++/c# templates to classic tasks."""
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent / 'data' / 'knowledge' / 'code_tasks'


def load(name):
    with open(BASE / name, encoding='utf-8') as fh:
        return json.load(fh)


def save(name, data):
    with open(BASE / name, 'w', encoding='utf-8') as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write('\n')


def task(data, tid):
    items = data.get('tasks', []) if isinstance(data, dict) else data
    for t in items:
        if t['task'] == tid:
            return t
    raise KeyError(tid)


def add(data, tid, langs):
    t = task(data, tid)
    t['languages'].update(langs)


d13 = load('13_python_utils.json')
d15 = load('15_ds_advanced.json')

# ── stack ──────────────────────────────────────────────────────────────────
add(d15, 'stack', {
    'go': 'package main\n\ntype Stack struct {\n    items []int\n}\n\nfunc (s *Stack) Push(v int) {\n    s.items = append(s.items, v)\n}\n\nfunc (s *Stack) Pop() int {\n    if len(s.items) == 0 {\n        panic("pop from empty stack")\n    }\n    top := s.items[len(s.items)-1]\n    s.items = s.items[:len(s.items)-1]\n    return top\n}\n\nfunc (s *Stack) Peek() int {\n    return s.items[len(s.items)-1]\n}\n\nfunc (s *Stack) IsEmpty() bool {\n    return len(s.items) == 0\n}',
    'rust': 'pub struct Stack<T> {\n    items: Vec<T>,\n}\n\nimpl<T> Stack<T> {\n    pub fn new() -> Self {\n        Stack { items: Vec::new() }\n    }\n    pub fn push(&mut self, v: T) {\n        self.items.push(v);\n    }\n    pub fn pop(&mut self) -> Option<T> {\n        self.items.pop()\n    }\n    pub fn peek(&self) -> Option<&T> {\n        self.items.last()\n    }\n    pub fn is_empty(&self) -> bool {\n        self.items.is_empty()\n    }\n}',
    'java': 'import java.util.ArrayDeque;\nimport java.util.Deque;\n\npublic class Stack {\n    private final Deque<Integer> items = new ArrayDeque<>();\n\n    public void push(int v) { items.push(v); }\n\n    public int pop() {\n        if (items.isEmpty()) throw new IllegalStateException("empty");\n        return items.pop();\n    }\n\n    public int peek() { return items.peek(); }\n\n    public boolean isEmpty() { return items.isEmpty(); }\n}',
    'c++': '#include <vector>\n#include <stdexcept>\n\ntemplate <typename T>\nclass Stack {\n    std::vector<T> items;\npublic:\n    void push(const T& v) { items.push_back(v); }\n    T pop() {\n        if (items.empty()) throw std::runtime_error("empty");\n        T top = items.back();\n        items.pop_back();\n        return top;\n    }\n    T& peek() { return items.back(); }\n    bool empty() const { return items.empty(); }\n};',
    'c#': 'public class Stack<T>\n{\n    private readonly List<T> _items = new();\n\n    public void Push(T v) => _items.Add(v);\n    public T Pop()\n    {\n        if (_items.Count == 0) throw new InvalidOperationException("empty");\n        T top = _items[^1];\n        _items.RemoveAt(_items.Count - 1);\n        return top;\n    }\n    public T Peek() => _items[^1];\n    public bool IsEmpty => _items.Count == 0;\n}',
})

# ── queue ──────────────────────────────────────────────────────────────────
add(d15, 'queue', {
    'go': 'package main\n\ntype Queue struct {\n    items []int\n    head  int\n}\n\nfunc (q *Queue) Enqueue(v int) {\n    q.items = append(q.items, v)\n}\n\nfunc (q *Queue) Dequeue() int {\n    if q.head >= len(q.items) {\n        panic("dequeue from empty queue")\n    }\n    v := q.items[q.head]\n    q.head++\n    if q.head > 1000 && q.head*2 > len(q.items) {\n        q.items = q.items[q.head:]\n        q.head = 0\n    }\n    return v\n}\n\nfunc (q *Queue) IsEmpty() bool { return q.head >= len(q.items) }',
    'rust': 'use std::collections::VecDeque;\n\npub struct Queue<T> {\n    items: VecDeque<T>,\n}\n\nimpl<T> Queue<T> {\n    pub fn new() -> Self {\n        Queue { items: VecDeque::new() }\n    }\n    pub fn enqueue(&mut self, v: T) {\n        self.items.push_back(v);\n    }\n    pub fn dequeue(&mut self) -> Option<T> {\n        self.items.pop_front()\n    }\n    pub fn is_empty(&self) -> bool {\n        self.items.is_empty()\n    }\n}',
    'java': 'import java.util.ArrayDeque;\nimport java.util.Queue;\n\npublic class IntQueue {\n    private final java.util.Queue<Integer> items = new ArrayDeque<>();\n\n    public void enqueue(int v) { items.offer(v); }\n    public int dequeue() {\n        Integer v = items.poll();\n        if (v == null) throw new IllegalStateException("empty");\n        return v;\n    }\n    public boolean isEmpty() { return items.isEmpty(); }\n}',
    'c++': '#include <queue>\n#include <stdexcept>\n\ntemplate <typename T>\nclass Queue {\n    std::queue<T> items;\npublic:\n    void enqueue(const T& v) { items.push(v); }\n    T dequeue() {\n        if (items.empty()) throw std::runtime_error("empty");\n        T front = items.front();\n        items.pop();\n        return front;\n    }\n    bool empty() const { return items.empty(); }\n};',
    'c#': 'public class Queue<T>\n{\n    private readonly System.Collections.Generic.Queue<T> _items = new();\n    public void Enqueue(T v) => _items.Enqueue(v);\n    public T Dequeue() => _items.Dequeue();\n    public bool IsEmpty => _items.Count == 0;\n}',
})

# ── trie ───────────────────────────────────────────────────────────────────
add(d15, 'trie', {
    'go': 'package main\n\ntype TrieNode struct {\n    children map[byte]*TrieNode\n    isEnd    bool\n}\n\ntype Trie struct {\n    root *TrieNode\n}\n\nfunc NewTrie() *Trie {\n    return &Trie{root: &TrieNode{children: map[byte]*TrieNode{}}}\n}\n\nfunc (t *Trie) Insert(word string) {\n    node := t.root\n    for i := 0; i < len(word); i++ {\n        ch := word[i]\n        if node.children[ch] == nil {\n            node.children[ch] = &TrieNode{children: map[byte]*TrieNode{}}\n        }\n        node = node.children[ch]\n    }\n    node.isEnd = true\n}\n\nfunc (t *Trie) Search(word string) bool {\n    node := t.find(word)\n    return node != nil && node.isEnd\n}\n\nfunc (t *Trie) StartsWith(prefix string) bool {\n    return t.find(prefix) != nil\n}\n\nfunc (t *Trie) find(s string) *TrieNode {\n    node := t.root\n    for i := 0; i < len(s); i++ {\n        if node.children[s[i]] == nil {\n            return nil\n        }\n        node = node.children[s[i]]\n    }\n    return node\n}',
    'rust': 'use std::collections::HashMap;\n\n#[derive(Default)]\npub struct TrieNode {\n    children: HashMap<char, TrieNode>,\n    is_end: bool,\n}\n\n#[derive(Default)]\npub struct Trie {\n    root: TrieNode,\n}\n\nimpl Trie {\n    pub fn new() -> Self {\n        Trie::default()\n    }\n\n    pub fn insert(&mut self, word: &str) {\n        let mut node = &mut self.root;\n        for ch in word.chars() {\n            node = node.children.entry(ch).or_default();\n        }\n        node.is_end = true;\n    }\n\n    pub fn search(&self, word: &str) -> bool {\n        self.find(word).map_or(false, |n| n.is_end)\n    }\n\n    pub fn starts_with(&self, prefix: &str) -> bool {\n        self.find(prefix).is_some()\n    }\n\n    fn find(&self, s: &str) -> Option<&TrieNode> {\n        let mut node = &self.root;\n        for ch in s.chars() {\n            node = node.children.get(&ch)?;\n        }\n        Some(node)\n    }\n}',
    'java': 'import java.util.HashMap;\nimport java.util.Map;\n\nclass TrieNode {\n    Map<Character, TrieNode> children = new HashMap<>();\n    boolean isEnd;\n}\n\npublic class Trie {\n    private final TrieNode root = new TrieNode();\n\n    public void insert(String word) {\n        TrieNode node = root;\n        for (char ch : word.toCharArray()) {\n            node = node.children.computeIfAbsent(ch, k -> new TrieNode());\n        }\n        node.isEnd = true;\n    }\n\n    public boolean search(String word) {\n        TrieNode node = find(word);\n        return node != null && node.isEnd;\n    }\n\n    public boolean startsWith(String prefix) {\n        return find(prefix) != null;\n    }\n\n    private TrieNode find(String s) {\n        TrieNode node = root;\n        for (char ch : s.toCharArray()) {\n            node = node.children.get(ch);\n            if (node == null) return null;\n        }\n        return node;\n    }\n}',
    'c++': '#include <unordered_map>\n#include <string>\n\nclass TrieNode {\npublic:\n    std::unordered_map<char, TrieNode*> children;\n    bool isEnd = false;\n    ~TrieNode() {\n        for (auto& [ch, child] : children) delete child;\n    }\n};\n\nclass Trie {\n    TrieNode root;\n    TrieNode* find(const std::string& s) {\n        TrieNode* node = &root;\n        for (char ch : s) {\n            if (!node->children.count(ch)) return nullptr;\n            node = node->children[ch];\n        }\n        return node;\n    }\npublic:\n    void insert(const std::string& word) {\n        TrieNode* node = &root;\n        for (char ch : word) {\n            if (!node->children.count(ch)) node->children[ch] = new TrieNode();\n            node = node->children[ch];\n        }\n        node->isEnd = true;\n    }\n    bool search(const std::string& word) {\n        TrieNode* node = find(word);\n        return node && node->isEnd;\n    }\n    bool startsWith(const std::string& prefix) {\n        return find(prefix) != nullptr;\n    }\n};',
    'c#': 'using System.Collections.Generic;\n\npublic class TrieNode\n{\n    public Dictionary<char, TrieNode> Children { get; } = new();\n    public bool IsEnd { get; set; }\n}\n\npublic class Trie\n{\n    private readonly TrieNode _root = new();\n\n    public void Insert(string word)\n    {\n        TrieNode node = _root;\n        foreach (char ch in word)\n        {\n            if (!node.Children.TryGetValue(ch, out var next))\n            {\n                next = new TrieNode();\n                node.Children[ch] = next;\n            }\n            node = next;\n        }\n        node.IsEnd = true;\n    }\n\n    public bool Search(string word) => Find(word)?.IsEnd ?? false;\n    public bool StartsWith(string prefix) => Find(prefix) != null;\n\n    private TrieNode? Find(string s)\n    {\n        TrieNode node = _root;\n        foreach (char ch in s)\n        {\n            if (!node.Children.TryGetValue(ch, out node)) return null;\n        }\n        return node;\n    }\n}',
})

# ── min_heap ───────────────────────────────────────────────────────────────
add(d15, 'min_heap', {
    'go': 'package main\n\nimport "container/heap"\n\n// IntHeap implements heap.Interface (min-heap of ints):\ntype IntHeap []int\n\nfunc (h IntHeap) Len() int            { return len(h) }\nfunc (h IntHeap) Less(i, j int) bool  { return h[i] < h[j] }\nfunc (h IntHeap) Swap(i, j int)       { h[i], h[j] = h[j], h[i] }\nfunc (h *IntHeap) Push(x any)         { *h = append(*h, x.(int)) }\nfunc (h *IntHeap) Pop() any {\n    old := *h\n    n := len(old)\n    v := old[n-1]\n    *h = old[:n-1]\n    return v\n}\n\nfunc main() {\n    h := &IntHeap{5, 1, 3}\n    heap.Init(h)\n    heap.Push(h, 2)\n    smallest := heap.Pop(h)   // 1\n    _ = smallest\n}',
    'rust': 'use std::collections::BinaryHeap;\nuse std::cmp::Reverse;\n\n// BinaryHeap is a MAX heap; wrap with Reverse for a min heap:\nlet mut heap: BinaryHeap<Reverse<i32>> = BinaryHeap::new();\nheap.push(Reverse(5));\nheap.push(Reverse(1));\nheap.push(Reverse(3));\nlet smallest = heap.pop().unwrap().0;   // 1',
    'java': 'import java.util.PriorityQueue;\n\n// PriorityQueue is a min-heap by default:\nPriorityQueue<Integer> heap = new PriorityQueue<>();\nheap.offer(5);\nheap.offer(1);\nheap.offer(3);\nint smallest = heap.poll();   // 1\n\n// Max-heap: PriorityQueue<>(Collections.reverseOrder())',
    'c++': '#include <queue>\n#include <vector>\n\n// priority_queue is a MAX heap; the greater<> comparator makes it a min heap:\nstd::priority_queue<int, std::vector<int>, std::greater<int>> minHeap;\nminHeap.push(5);\nminHeap.push(1);\nminHeap.push(3);\nint smallest = minHeap.top();   // 1\nminHeap.pop();\n\n// Default (max) heap:\nstd::priority_queue<int> maxHeap;',
    'c#': '// .NET 6+: PriorityQueue<TElement, TPriority>\nvar heap = new PriorityQueue<int, int>();\nheap.Enqueue(5, 5);\nheap.Enqueue(1, 1);\nheap.Enqueue(3, 3);\nint smallest = heap.Dequeue();   // 1',
})

# ── lru_cache ──────────────────────────────────────────────────────────────
add(d15, 'lru_cache', {
    'go': 'package main\n\nimport "container/list"\n\ntype entry struct {\n    key   int\n    value int\n}\n\ntype LRUCache struct {\n    capacity int\n    items    map[int]*list.Element\n    order    *list.List\n}\n\nfunc NewLRUCache(capacity int) *LRUCache {\n    return &LRUCache{capacity: capacity, items: map[int]*list.Element{}, order: list.New()}\n}\n\nfunc (c *LRUCache) Get(key int) int {\n    el, ok := c.items[key]\n    if !ok {\n        return -1\n    }\n    c.order.MoveToFront(el)\n    return el.Value.(*entry).value\n}\n\nfunc (c *LRUCache) Put(key, value int) {\n    if el, ok := c.items[key]; ok {\n        el.Value.(*entry).value = value\n        c.order.MoveToFront(el)\n        return\n    }\n    el := c.order.PushFront(&entry{key: key, value: value})\n    c.items[key] = el\n    if len(c.items) > c.capacity {\n        last := c.order.Back()\n        c.order.Remove(last)\n        delete(c.items, last.Value.(*entry).key)\n    }\n}',
    'rust': 'use std::collections::HashMap;\n\n// Simplified O(1)-ish LRU: HashMap + recency re-insertion.\npub struct LRUCache {\n    capacity: usize,\n    items: HashMap<i32, i32>,\n    recency: Vec<i32>,   // front = most recent\n}\n\nimpl LRUCache {\n    pub fn new(capacity: i32) -> Self {\n        LRUCache { capacity: capacity as usize, items: HashMap::new(), recency: Vec::new() }\n    }\n\n    pub fn get(&mut self, key: i32) -> i32 {\n        match self.items.get(&key) {\n            Some(&v) => {\n                self.recency.retain(|&k| k != key);\n                self.recency.insert(0, key);\n                v\n            }\n            None => -1,\n        }\n    }\n\n    pub fn put(&mut self, key: i32, value: i32) {\n        if !self.items.contains_key(&key) {\n            self.recency.retain(|&k| k != key);\n            self.recency.insert(0, key);\n        }\n        self.items.insert(key, value);\n        if self.items.len() > self.capacity {\n            if let Some(oldest) = self.recency.pop() {\n                self.items.remove(&oldest);\n            }\n        }\n    }\n}',
    'java': 'import java.util.LinkedHashMap;\nimport java.util.Map;\n\npublic class LRUCache {\n    private final LinkedHashMap<Integer, Integer> map;\n\n    public LRUCache(int capacity) {\n        map = new LinkedHashMap<>(16, 0.75f, true) {   // accessOrder = true\n            @Override\n            protected boolean removeEldestEntry(Map.Entry<Integer, Integer> eldest) {\n                return size() > capacity;\n            }\n        };\n    }\n\n    public int get(int key) {\n        return map.getOrDefault(key, -1);\n    }\n\n    public void put(int key, int value) {\n        map.put(key, value);\n    }\n}',
    'c++': '#include <list>\n#include <unordered_map>\n\nclass LRUCache {\n    std::list<std::pair<int, int>> order;   // front = most recent\n    std::unordered_map<int, std::list<std::pair<int, int>>::iterator> items;\n    int capacity;\n\npublic:\n    LRUCache(int cap) : capacity(cap) {}\n\n    int get(int key) {\n        auto it = items.find(key);\n        if (it == items.end()) return -1;\n        order.splice(order.begin(), order, it->second);\n        return it->second->second;\n    }\n\n    void put(int key, int value) {\n        auto it = items.find(key);\n        if (it != items.end()) {\n            it->second->second = value;\n            order.splice(order.begin(), order, it->second);\n            return;\n        }\n        order.push_front({key, value});\n        items[key] = order.begin();\n        if (items.size() > capacity) {\n            items.erase(order.back().first);\n            order.pop_back();\n        }\n    }\n};',
    'c#': 'using System.Collections.Generic;\n\npublic class LRUCache\n{\n    private readonly int _capacity;\n    private readonly Dictionary<int, LinkedListNode<(int key, int value)>> _map = new();\n    private readonly LinkedList<(int key, int value)> _list = new();\n\n    public LRUCache(int capacity) => _capacity = capacity;\n\n    public int Get(int key)\n    {\n        if (!_map.TryGetValue(key, out var node)) return -1;\n        _list.Remove(node);\n        _list.AddFirst(node);\n        return node.Value.value;\n    }\n\n    public void Put(int key, int value)\n    {\n        if (_map.TryGetValue(key, out var node))\n        {\n            node.Value = (key, value);\n            _list.Remove(node);\n            _list.AddFirst(node);\n            return;\n        }\n        var newNode = _list.AddFirst((key, value));\n        _map[key] = newNode;\n        if (_map.Count > _capacity)\n        {\n            _map.Remove(_list.Last.Value.key);\n            _list.RemoveLast();\n        }\n    }\n}',
})

# ── merge_intervals ────────────────────────────────────────────────────────
add(d15, 'merge_intervals', {
    'go': 'package main\n\nimport "sort"\n\nfunc MergeIntervals(intervals [][]int) [][]int {\n    if len(intervals) == 0 {\n        return nil\n    }\n    sort.Slice(intervals, func(i, j int) bool { return intervals[i][0] < intervals[j][0] })\n    merged := [][]int{intervals[0]}\n    for _, iv := range intervals[1:] {\n        last := merged[len(merged)-1]\n        if iv[0] <= last[1] {\n            if iv[1] > last[1] {\n                last[1] = iv[1]\n            }\n        } else {\n            merged = append(merged, iv)\n        }\n    }\n    return merged\n}',
    'rust': 'pub fn merge_intervals(intervals: Vec<Vec<i32>>) -> Vec<Vec<i32>> {\n    if intervals.is_empty() {\n        return vec![];\n    }\n    let mut intervals = intervals;\n    intervals.sort_by_key(|iv| iv[0]);\n    let mut merged: Vec<Vec<i32>> = vec![intervals[0].clone()];\n    for iv in intervals.into_iter().skip(1) {\n        let last = merged.last_mut().unwrap();\n        if iv[0] <= last[1] {\n            last[1] = last[1].max(iv[1]);\n        } else {\n            merged.push(iv);\n        }\n    }\n    merged\n}',
    'java': 'import java.util.*;\n\npublic static int[][] mergeIntervals(int[][] intervals) {\n    if (intervals.length == 0) return new int[0][];\n    Arrays.sort(intervals, (a, b) -> a[0] - b[0]);\n    List<int[]> merged = new ArrayList<>();\n    merged.add(intervals[0]);\n    for (int i = 1; i < intervals.length; i++) {\n        int[] last = merged.get(merged.size() - 1);\n        if (intervals[i][0] <= last[1]) {\n            last[1] = Math.max(last[1], intervals[i][1]);\n        } else {\n            merged.add(intervals[i]);\n        }\n    }\n    return merged.toArray(new int[0][]);\n}',
    'c++': '#include <vector>\n#include <algorithm>\n\nstd::vector<std::vector<int>> mergeIntervals(std::vector<std::vector<int>> intervals) {\n    if (intervals.empty()) return {};\n    std::sort(intervals.begin(), intervals.end());\n    std::vector<std::vector<int>> merged;\n    for (const auto& iv : intervals) {\n        if (merged.empty() || iv[0] > merged.back()[1]) {\n            merged.push_back(iv);\n        } else {\n            merged.back()[1] = std::max(merged.back()[1], iv[1]);\n        }\n    }\n    return merged;\n}',
    'c#': 'public int[][] MergeIntervals(int[][] intervals)\n{\n    if (intervals.Length == 0) return Array.Empty<int[]>();\n    Array.Sort(intervals, (a, b) => a[0].CompareTo(b[0]));\n    var merged = new List<int[]> { intervals[0] };\n    foreach (var iv in intervals.Skip(1))\n    {\n        var last = merged[^1];\n        if (iv[0] <= last[1]) last[1] = Math.Max(last[1], iv[1]);\n        else merged.Add(iv);\n    }\n    return merged.ToArray();\n}',
})

# ── longest_common_prefix ──────────────────────────────────────────────────
add(d16 := load('16_strings_adv.json'), 'longest_common_prefix', {
    'go': 'package main\n\nimport "strings"\n\nfunc LongestCommonPrefix(strs []string) string {\n    if len(strs) == 0 {\n        return ""\n    }\n    prefix := strs[0]\n    for _, s := range strs[1:] {\n        for !strings.HasPrefix(s, prefix) {\n            prefix = prefix[:len(prefix)-1]\n            if prefix == "" {\n                return ""\n            }\n        }\n    }\n    return prefix\n}',
    'rust': 'pub fn longest_common_prefix(strs: &[String]) -> String {\n    if strs.is_empty() {\n        return String::new();\n    }\n    let mut prefix = strs[0].clone();\n    for s in &strs[1..] {\n        while !s.starts_with(&prefix) {\n            prefix.pop();\n            if prefix.is_empty() {\n                return prefix;\n            }\n        }\n    }\n    prefix\n}',
    'java': 'public static String longestCommonPrefix(String[] strs) {\n    if (strs.length == 0) return "";\n    String prefix = strs[0];\n    for (int i = 1; i < strs.length; i++) {\n        while (!strs[i].startsWith(prefix)) {\n            prefix = prefix.substring(0, prefix.length() - 1);\n            if (prefix.isEmpty()) return "";\n        }\n    }\n    return prefix;\n}',
    'c++': '#include <string>\n#include <vector>\n\nstd::string longestCommonPrefix(const std::vector<std::string>& strs) {\n    if (strs.empty()) return "";\n    std::string prefix = strs[0];\n    for (size_t i = 1; i < strs.size(); i++) {\n        while (strs[i].rfind(prefix, 0) != 0) {   // starts_with\n            prefix.pop_back();\n            if (prefix.empty()) return prefix;\n        }\n    }\n    return prefix;\n}',
    'c#': 'public static string LongestCommonPrefix(string[] strs)\n{\n    if (strs.Length == 0) return "";\n    string prefix = strs[0];\n    for (int i = 1; i < strs.Length; i++)\n    {\n        while (!strs[i].StartsWith(prefix))\n        {\n            prefix = prefix[..^1];\n            if (prefix.Length == 0) return prefix;\n        }\n    }\n    return prefix;\n}',
})
save('16_strings_adv.json', d16)

# ── edit_distance / reverse_words / count_vowels ───────────────────────────
add(d13, 'edit_distance', {
    'go': 'package main\n\nfunc EditDistance(a, b string) int {\n    m, n := len(a), len(b)\n    dp := make([][]int, m+1)\n    for i := range dp {\n        dp[i] = make([]int, n+1)\n        dp[i][0] = i\n    }\n    for j := 0; j <= n; j++ {\n        dp[0][j] = j\n    }\n    for i := 1; i <= m; i++ {\n        for j := 1; j <= n; j++ {\n            if a[i-1] == b[j-1] {\n                dp[i][j] = dp[i-1][j-1]\n            } else {\n                dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n            }\n        }\n    }\n    return dp[m][n]\n}\n\nfunc min(xs ...int) int {\n    best := xs[0]\n    for _, x := range xs[1:] {\n        if x < best {\n            best = x\n        }\n    }\n    return best\n}',
    'rust': 'pub fn edit_distance(a: &str, b: &str) -> usize {\n    let (m, n) = (a.len(), b.len());\n    let mut dp = vec![vec![0usize; n + 1]; m + 1];\n    for i in 0..=m { dp[i][0] = i; }\n    for j in 0..=n { dp[0][j] = j; }\n    for i in 1..=m {\n        for j in 1..=n {\n            dp[i][j] = if a.as_bytes()[i - 1] == b.as_bytes()[j - 1] {\n                dp[i - 1][j - 1]\n            } else {\n                1 + dp[i - 1][j].min(dp[i][j - 1]).min(dp[i - 1][j - 1])\n            };\n        }\n    }\n    dp[m][n]\n}',
    'java': 'public static int editDistance(String a, String b) {\n    int m = a.length(), n = b.length();\n    int[][] dp = new int[m + 1][n + 1];\n    for (int i = 0; i <= m; i++) dp[i][0] = i;\n    for (int j = 0; j <= n; j++) dp[0][j] = j;\n    for (int i = 1; i <= m; i++) {\n        for (int j = 1; j <= n; j++) {\n            if (a.charAt(i - 1) == b.charAt(j - 1)) {\n                dp[i][j] = dp[i - 1][j - 1];\n            } else {\n                dp[i][j] = 1 + Math.min(dp[i - 1][j], Math.min(dp[i][j - 1], dp[i - 1][j - 1]));\n            }\n        }\n    }\n    return dp[m][n];\n}',
    'c++': '#include <string>\n#include <vector>\n#include <algorithm>\n\nint editDistance(const std::string& a, const std::string& b) {\n    int m = a.size(), n = b.size();\n    std::vector<std::vector<int>> dp(m + 1, std::vector<int>(n + 1));\n    for (int i = 0; i <= m; i++) dp[i][0] = i;\n    for (int j = 0; j <= n; j++) dp[0][j] = j;\n    for (int i = 1; i <= m; i++) {\n        for (int j = 1; j <= n; j++) {\n            if (a[i - 1] == b[j - 1]) dp[i][j] = dp[i - 1][j - 1];\n            else dp[i][j] = 1 + std::min({dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]});\n        }\n    }\n    return dp[m][n];\n}',
    'c#': 'public static int EditDistance(string a, string b)\n{\n    int m = a.Length, n = b.Length;\n    var dp = new int[m + 1, n + 1];\n    for (int i = 0; i <= m; i++) dp[i, 0] = i;\n    for (int j = 0; j <= n; j++) dp[0, j] = j;\n    for (int i = 1; i <= m; i++)\n        for (int j = 1; j <= n; j++)\n            dp[i, j] = a[i - 1] == b[j - 1]\n                ? dp[i - 1, j - 1]\n                : 1 + Math.Min(dp[i - 1, j], Math.Min(dp[i, j - 1], dp[i - 1, j - 1]));\n    return dp[m, n];\n}',
})

add(d16, 'reverse_words', {
    'go': 'package main\n\nimport "strings"\n\nfunc ReverseWords(sentence string) string {\n    words := strings.Fields(sentence)\n    for i, j := 0, len(words)-1; i < j; i, j = i+1, j-1 {\n        words[i], words[j] = words[j], words[i]\n    }\n    return strings.Join(words, " ")\n}',
    'rust': 'pub fn reverse_words(sentence: &str) -> String {\n    sentence.split_whitespace().rev().collect::<Vec<_>>().join(" ")\n}',
    'java': 'public static String reverseWords(String sentence) {\n    String[] words = sentence.trim().split("\\\\s+");\n    Collections.reverse(Arrays.asList(words));\n    return String.join(" ", words);\n}',
    'c++': '#include <string>\n#include <sstream>\n#include <vector>\n\nstd::string reverseWords(const std::string& sentence) {\n    std::istringstream in(sentence);\n    std::vector<std::string> words;\n    std::string w;\n    while (in >> w) words.push_back(w);\n    std::reverse(words.begin(), words.end());\n    std::string out;\n    for (size_t i = 0; i < words.size(); i++) {\n        if (i) out += " ";\n        out += words[i];\n    }\n    return out;\n}',
    'c#': 'public static string ReverseWords(string sentence)\n{\n    var words = sentence.Split(\' \', StringSplitOptions.RemoveEmptyEntries);\n    Array.Reverse(words);\n    return string.Join(" ", words);\n}',
})

add(d13, 'count_vowels', {
    'go': 'package main\n\nimport "strings"\n\nfunc CountVowels(s string) int {\n    count := 0\n    for _, ch := range strings.ToLower(s) {\n        if strings.ContainsRune("aeiou", ch) {\n            count++\n        }\n    }\n    return count\n}',
    'rust': 'pub fn count_vowels(s: &str) -> usize {\n    s.chars().filter(|c| "aeiouAEIOU".contains(*c)).count()\n}',
    'java': 'public static int countVowels(String s) {\n    int count = 0;\n    for (char ch : s.toLowerCase().toCharArray()) {\n        if ("aeiou".indexOf(ch) >= 0) count++;\n    }\n    return count;\n}',
    'c++': '#include <string>\n#include <cctype>\n\nint countVowels(const std::string& s) {\n    int count = 0;\n    for (char ch : s) {\n        ch = std::tolower(ch);\n        if (ch == \'a\' || ch == \'e\' || ch == \'i\' || ch == \'o\' || ch == \'u\') count++;\n    }\n    return count;\n}',
    'c#': 'public static int CountVowels(string s)\n{\n    return s.ToLower().Count(c => "aeiou".Contains(c));\n}',
})

# ── queue_two_stacks / find_duplicates / first_unique_char / quicksort ─────
add(d15, 'queue_two_stacks', {
    'go': 'package main\n\ntype QueueWithStacks struct {\n    stackIn  []int\n    stackOut []int\n}\n\nfunc (q *QueueWithStacks) Enqueue(v int) {\n    q.stackIn = append(q.stackIn, v)\n}\n\nfunc (q *QueueWithStacks) Dequeue() int {\n    if len(q.stackOut) == 0 {\n        for len(q.stackIn) > 0 {\n            n := len(q.stackIn) - 1\n            q.stackOut = append(q.stackOut, q.stackIn[n])\n            q.stackIn = q.stackIn[:n]\n        }\n    }\n    if len(q.stackOut) == 0 {\n        panic("empty queue")\n    }\n    n := len(q.stackOut) - 1\n    v := q.stackOut[n]\n    q.stackOut = q.stackOut[:n]\n    return v\n}',
    'rust': 'pub struct QueueWithStacks<T> {\n    stack_in: Vec<T>,\n    stack_out: Vec<T>,\n}\n\nimpl<T> QueueWithStacks<T> {\n    pub fn new() -> Self {\n        QueueWithStacks { stack_in: Vec::new(), stack_out: Vec::new() }\n    }\n    pub fn enqueue(&mut self, v: T) {\n        self.stack_in.push(v);\n    }\n    pub fn dequeue(&mut self) -> Option<T> {\n        if self.stack_out.is_empty() {\n            while let Some(v) = self.stack_in.pop() {\n                self.stack_out.push(v);\n            }\n        }\n        self.stack_out.pop()\n    }\n}',
    'java': 'import java.util.ArrayDeque;\nimport java.util.Deque;\n\npublic class QueueWithStacks {\n    private final Deque<Integer> stackIn = new ArrayDeque<>();\n    private final Deque<Integer> stackOut = new ArrayDeque<>();\n\n    public void enqueue(int v) { stackIn.push(v); }\n\n    public int dequeue() {\n        if (stackOut.isEmpty()) {\n            while (!stackIn.isEmpty()) stackOut.push(stackIn.pop());\n        }\n        if (stackOut.isEmpty()) throw new IllegalStateException("empty");\n        return stackOut.pop();\n    }\n}',
    'c++': '#include <stack>\n#include <stdexcept>\n\ntemplate <typename T>\nclass QueueWithStacks {\n    std::stack<T> stackIn, stackOut;\npublic:\n    void enqueue(const T& v) { stackIn.push(v); }\n    T dequeue() {\n        if (stackOut.empty()) {\n            while (!stackIn.empty()) { stackOut.push(stackIn.top()); stackIn.pop(); }\n        }\n        if (stackOut.empty()) throw std::runtime_error("empty");\n        T v = stackOut.top();\n        stackOut.pop();\n        return v;\n    }\n};',
    'c#': 'public class QueueWithStacks<T>\n{\n    private readonly Stack<T> _stackIn = new();\n    private readonly Stack<T> _stackOut = new();\n\n    public void Enqueue(T v) => _stackIn.Push(v);\n\n    public T Dequeue()\n    {\n        if (_stackOut.Count == 0)\n            while (_stackIn.Count > 0) _stackOut.Push(_stackIn.Pop());\n        return _stackOut.Pop();\n    }\n}',
})

add(d13, 'find_duplicates', {
    'go': 'package main\n\nfunc FindDuplicates(items []int) []int {\n    seen := map[int]bool{}\n    dupes := map[int]bool{}\n    out := []int{}\n    for _, v := range items {\n        if seen[v] && !dupes[v] {\n            dupes[v] = true\n            out = append(out, v)\n        }\n        seen[v] = true\n    }\n    return out\n}',
    'rust': 'use std::collections::HashSet;\n\npub fn find_duplicates(items: &[i32]) -> Vec<i32> {\n    let mut seen = HashSet::new();\n    let mut dupes = HashSet::new();\n    let mut out = Vec::new();\n    for &v in items {\n        if seen.contains(&v) && dupes.insert(v) {\n            out.push(v);\n        }\n        seen.insert(v);\n    }\n    out\n}',
    'java': 'import java.util.*;\n\npublic static List<Integer> findDuplicates(List<Integer> items) {\n    Set<Integer> seen = new HashSet<>();\n    Set<Integer> dupes = new HashSet<>();\n    List<Integer> out = new ArrayList<>();\n    for (int v : items) {\n        if (seen.contains(v) && dupes.add(v)) out.add(v);\n        seen.add(v);\n    }\n    return out;\n}',
    'c++': '#include <vector>\n#include <unordered_set>\n\nstd::vector<int> findDuplicates(const std::vector<int>& items) {\n    std::unordered_set<int> seen, dupes;\n    std::vector<int> out;\n    for (int v : items) {\n        if (seen.count(v) && dupes.insert(v).second) out.push_back(v);\n        seen.insert(v);\n    }\n    return out;\n}',
    'c#': 'public static List<int> FindDuplicates(List<int> items)\n{\n    var seen = new HashSet<int>();\n    var dupes = new HashSet<int>();\n    var out = new List<int>();\n    foreach (int v in items)\n    {\n        if (seen.Contains(v) && dupes.Add(v)) out.Add(v);\n        seen.Add(v);\n    }\n    return out;\n}',
})

add(d15, 'first_unique_char', {
    'go': 'package main\n\nfunc FirstUniqueChar(s string) byte {\n    counts := make(map[byte]int)\n    for i := 0; i < len(s); i++ {\n        counts[s[i]]++\n    }\n    for i := 0; i < len(s); i++ {\n        if counts[s[i]] == 1 {\n            return s[i]\n        }\n    }\n    return 0\n}',
    'rust': 'use std::collections::HashMap;\n\npub fn first_unique_char(s: &str) -> Option<char> {\n    let mut counts = HashMap::new();\n    for ch in s.chars() {\n        *counts.entry(ch).or_insert(0) += 1;\n    }\n    s.chars().find(|ch| counts[ch] == 1)\n}',
    'java': 'import java.util.LinkedHashMap;\nimport java.util.Map;\n\npublic static Character firstUniqueChar(String s) {\n    Map<Character, Integer> counts = new LinkedHashMap<>();\n    for (char ch : s.toCharArray()) counts.merge(ch, 1, Integer::sum);\n    for (var e : counts.entrySet()) {\n        if (e.getValue() == 1) return e.getKey();\n    }\n    return null;\n}',
    'c++': '#include <string>\n#include <unordered_map>\n\nchar firstUniqueChar(const std::string& s) {\n    std::unordered_map<char, int> counts;\n    for (char ch : s) counts[ch]++;\n    for (char ch : s) {\n        if (counts[ch] == 1) return ch;\n    }\n    return 0;\n}',
    'c#': 'public static char? FirstUniqueChar(string s)\n{\n    var counts = new Dictionary<char, int>();\n    foreach (char ch in s) counts[ch] = counts.GetValueOrDefault(ch) + 1;\n    return s.FirstOrDefault(ch => counts[ch] == 1);\n}',
})

add(d13, 'quicksort', {
    'go': 'package main\n\nfunc Quicksort(items []int) []int {\n    if len(items) <= 1 {\n        return items\n    }\n    pivot := items[len(items)/2]\n    var left, mid, right []int\n    for _, v := range items {\n        switch {\n        case v < pivot:\n            left = append(left, v)\n        case v == pivot:\n            mid = append(mid, v)\n        default:\n            right = append(right, v)\n        }\n    }\n    return append(append(Quicksort(left), mid...), Quicksort(right)...)\n}',
    'rust': 'pub fn quicksort<T: Ord + Clone>(items: &[T]) -> Vec<T> {\n    if items.len() <= 1 {\n        return items.to_vec();\n    }\n    let pivot = &items[items.len() / 2];\n    let mut left = Vec::new();\n    let mut mid = Vec::new();\n    let mut right = Vec::new();\n    for v in items {\n        match v.cmp(pivot) {\n            std::cmp::Ordering::Less => left.push(v.clone()),\n            std::cmp::Ordering::Equal => mid.push(v.clone()),\n            std::cmp::Ordering::Greater => right.push(v.clone()),\n        }\n    }\n    let mut out = quicksort(&left);\n    out.append(&mut mid);\n    out.append(&mut quicksort(&right));\n    out\n}',
    'java': 'public static List<Integer> quicksort(List<Integer> items) {\n    if (items.size() <= 1) return items;\n    int pivot = items.get(items.size() / 2);\n    List<Integer> left = new ArrayList<>(), mid = new ArrayList<>(), right = new ArrayList<>();\n    for (int v : items) {\n        if (v < pivot) left.add(v);\n        else if (v == pivot) mid.add(v);\n        else right.add(v);\n    }\n    List<Integer> out = new ArrayList<>(quicksort(left));\n    out.addAll(mid);\n    out.addAll(quicksort(right));\n    return out;\n}',
    'c++': '#include <vector>\n\ntemplate <typename T>\nstd::vector<T> quicksort(const std::vector<T>& items) {\n    if (items.size() <= 1) return items;\n    const T& pivot = items[items.size() / 2];\n    std::vector<T> left, mid, right;\n    for (const auto& v : items) {\n        if (v < pivot) left.push_back(v);\n        else if (v == pivot) mid.push_back(v);\n        else right.push_back(v);\n    }\n    auto out = quicksort(left);\n    out.insert(out.end(), mid.begin(), mid.end());\n    auto r = quicksort(right);\n    out.insert(out.end(), r.begin(), r.end());\n    return out;\n}',
    'c#': 'public static List<T> Quicksort<T>(List<T> items) where T : IComparable<T>\n{\n    if (items.Count <= 1) return items;\n    T pivot = items[items.Count / 2];\n    var left = new List<T>(); var mid = new List<T>(); var right = new List<T>();\n    foreach (T v in items)\n    {\n        if (v.CompareTo(pivot) < 0) left.Add(v);\n        else if (v.CompareTo(pivot) == 0) mid.Add(v);\n        else right.Add(v);\n    }\n    var out = Quicksort(left);\n    out.AddRange(mid);\n    out.AddRange(Quicksort(right));\n    return out;\n}',
})

# ── sliding_window_max / merge_sort / bfs / level_order / dijkstra ─────────
add(d13, 'sliding_window_max', {
    'go': 'package main\n\nfunc SlidingWindowMax(nums []int, k int) []int {\n    dq := []int{}   // indices with decreasing values\n    out := []int{}\n    for i, n := range nums {\n        for len(dq) > 0 && nums[dq[len(dq)-1]] <= n {\n            dq = dq[:len(dq)-1]\n        }\n        dq = append(dq, i)\n        if dq[0] <= i-k {\n            dq = dq[1:]\n        }\n        if i >= k-1 {\n            out = append(out, nums[dq[0]])\n        }\n    }\n    return out\n}',
    'rust': 'use std::collections::VecDeque;\n\npub fn sliding_window_max(nums: &[i32], k: usize) -> Vec<i32> {\n    let mut dq: VecDeque<usize> = VecDeque::new();\n    let mut out = Vec::new();\n    for i in 0..nums.len() {\n        while let Some(&last) = dq.back() {\n            if nums[last] <= nums[i] { dq.pop_back(); } else { break; }\n        }\n        dq.push_back(i);\n        if dq[0] <= i.saturating_sub(k) { dq.pop_front(); }\n        if i + 1 >= k { out.push(nums[dq[0]]); }\n    }\n    out\n}',
    'java': 'import java.util.*;\n\npublic static int[] slidingWindowMax(int[] nums, int k) {\n    Deque<Integer> dq = new ArrayDeque<>();   // indices, decreasing values\n    List<Integer> out = new ArrayList<>();\n    for (int i = 0; i < nums.length; i++) {\n        while (!dq.isEmpty() && nums[dq.peekLast()] <= nums[i]) dq.pollLast();\n        dq.offerLast(i);\n        if (dq.peekFirst() <= i - k) dq.pollFirst();\n        if (i >= k - 1) out.add(nums[dq.peekFirst()]);\n    }\n    return out.stream().mapToInt(Integer::intValue).toArray();\n}',
    'c++': '#include <vector>\n#include <deque>\n\nstd::vector<int> slidingWindowMax(const std::vector<int>& nums, int k) {\n    std::deque<int> dq;   // indices with decreasing values\n    std::vector<int> out;\n    for (int i = 0; i < (int)nums.size(); i++) {\n        while (!dq.empty() && nums[dq.back()] <= nums[i]) dq.pop_back();\n        dq.push_back(i);\n        if (dq.front() <= i - k) dq.pop_front();\n        if (i >= k - 1) out.push_back(nums[dq.front()]);\n    }\n    return out;\n}',
    'c#': 'public static int[] SlidingWindowMax(int[] nums, int k)\n{\n    var dq = new LinkedList<int>();   // indices with decreasing values\n    var out = new List<int>();\n    for (int i = 0; i < nums.Length; i++)\n    {\n        while (dq.Count > 0 && nums[dq.Last()] <= nums[i]) dq.RemoveLast();\n        dq.AddLast(i);\n        if (dq.First() <= i - k) dq.RemoveFirst();\n        if (i >= k - 1) out.Add(nums[dq.First()]);\n    }\n    return out.ToArray();\n}',
})

add(d13, 'merge_sort', {
    'go': 'package main\n\nfunc MergeSort(items []int) []int {\n    if len(items) <= 1 {\n        return items\n    }\n    mid := len(items) / 2\n    left := MergeSort(items[:mid])\n    right := MergeSort(items[mid:])\n    out := make([]int, 0, len(items))\n    i, j := 0, 0\n    for i < len(left) && j < len(right) {\n        if left[i] <= right[j] {\n            out = append(out, left[i]); i++\n        } else {\n            out = append(out, right[j]); j++\n        }\n    }\n    out = append(out, left[i:]...)\n    out = append(out, right[j:]...)\n    return out\n}',
    'rust': 'pub fn merge_sort<T: Ord + Clone>(items: &[T]) -> Vec<T> {\n    if items.len() <= 1 {\n        return items.to_vec();\n    }\n    let mid = items.len() / 2;\n    let left = merge_sort(&items[..mid]);\n    let right = merge_sort(&items[mid..]);\n    let mut out = Vec::with_capacity(items.len());\n    let (mut i, mut j) = (0, 0);\n    while i < left.len() && j < right.len() {\n        if left[i] <= right[j] { out.push(left[i].clone()); i += 1; }\n        else { out.push(right[j].clone()); j += 1; }\n    }\n    out.extend_from_slice(&left[i..]);\n    out.extend_from_slice(&right[j..]);\n    out\n}',
    'java': 'public static List<Integer> mergeSort(List<Integer> items) {\n    if (items.size() <= 1) return items;\n    int mid = items.size() / 2;\n    List<Integer> left = mergeSort(new ArrayList<>(items.subList(0, mid)));\n    List<Integer> right = mergeSort(new ArrayList<>(items.subList(mid, items.size())));\n    List<Integer> out = new ArrayList<>();\n    int i = 0, j = 0;\n    while (i < left.size() && j < right.size()) {\n        if (left.get(i) <= right.get(j)) out.add(left.get(i++));\n        else out.add(right.get(j++));\n    }\n    while (i < left.size()) out.add(left.get(i++));\n    while (j < right.size()) out.add(right.get(j++));\n    return out;\n}',
    'c++': '#include <vector>\n\ntemplate <typename T>\nstd::vector<T> mergeSort(const std::vector<T>& items) {\n    if (items.size() <= 1) return items;\n    size_t mid = items.size() / 2;\n    auto left = mergeSort(std::vector<T>(items.begin(), items.begin() + mid));\n    auto right = mergeSort(std::vector<T>(items.begin() + mid, items.end()));\n    std::vector<T> out;\n    size_t i = 0, j = 0;\n    while (i < left.size() && j < right.size()) {\n        if (left[i] <= right[j]) out.push_back(left[i++]);\n        else out.push_back(right[j++]);\n    }\n    out.insert(out.end(), left.begin() + i, left.end());\n    out.insert(out.end(), right.begin() + j, right.end());\n    return out;\n}',
    'c#': 'public static List<T> MergeSort<T>(List<T> items) where T : IComparable<T>\n{\n    if (items.Count <= 1) return items;\n    int mid = items.Count / 2;\n    var left = MergeSort(items.GetRange(0, mid));\n    var right = MergeSort(items.GetRange(mid, items.Count - mid));\n    var out = new List<T>();\n    int i = 0, j = 0;\n    while (i < left.Count && j < right.Count)\n        out.Add(left[i].CompareTo(right[j]) <= 0 ? left[i++] : right[j++]);\n    while (i < left.Count) out.Add(left[i++]);\n    while (j < right.Count) out.Add(right[j++]);\n    return out;\n}',
})

# dijkstra already got go+rust+java+c++ in 15? add the missing ones:
add(d15, 'dijkstra', {
    'go': 'package main\n\nimport "container/heap"\n\ntype item struct {\n    node string\n    dist int\n}\ntype pq []item\n\nfunc (p pq) Len() int            { return len(p) }\nfunc (p pq) Less(i, j int) bool  { return p[i].dist < p[j].dist }\nfunc (p pq) Swap(i, j int)       { p[i], p[j] = p[j], p[i] }\nfunc (p *pq) Push(x any)         { *p = append(*p, x.(item)) }\nfunc (p *pq) Pop() any {\n    old := *p\n    n := len(old)\n    v := old[n-1]\n    *p = old[:n-1]\n    return v\n}\n\nfunc Dijkstra(graph map[string][]item, start string) map[string]int {\n    dist := map[string]int{}\n    for node := range graph {\n        dist[node] = 1 << 60\n    }\n    dist[start] = 0\n    h := &pq{{start, 0}}\n    heap.Init(h)\n    for h.Len() > 0 {\n        cur := heap.Pop(h).(item)\n        if cur.dist > dist[cur.node] {\n            continue\n        }\n        for _, edge := range graph[cur.node] {\n            if nd := cur.dist + edge.dist; nd < dist[edge.node] {\n                dist[edge.node] = nd\n                heap.Push(h, item{edge.node, nd})\n            }\n        }\n    }\n    return dist\n}',
    'rust': 'use std::collections::{BinaryHeap, HashMap};\nuse std::cmp::Reverse;\n\npub fn dijkstra(graph: &HashMap<String, Vec<(String, u32)>>, start: &str) -> HashMap<String, u32> {\n    let mut dist: HashMap<String, u32> = graph.keys().map(|n| (n.clone(), u32::MAX)).collect();\n    dist.insert(start.to_string(), 0);\n    let mut heap = BinaryHeap::new();\n    heap.push(Reverse((0u32, start.to_string())));\n    while let Some(Reverse((d, node))) = heap.pop() {\n        if d > dist[&node] {\n            continue;\n        }\n        for (neighbor, w) in &graph[&node] {\n            let nd = d + w;\n            if nd < dist[neighbor] {\n                dist.insert(neighbor.clone(), nd);\n                heap.push(Reverse((nd, neighbor.clone())));\n            }\n        }\n    }\n    dist\n}',
    'java': 'import java.util.*;\n\npublic static Map<String, Integer> dijkstra(\n        Map<String, List<int[]>> graph, String start) {\n    Map<String, Integer> dist = new HashMap<>();\n    for (String node : graph.keySet()) dist.put(node, Integer.MAX_VALUE);\n    dist.put(start, 0);\n    PriorityQueue<int[]> pq = new PriorityQueue<>(Comparator.comparingInt(a -> a[1]));\n    pq.offer(new int[]{start.hashCode(), 0});   // (nodeHash, dist) — see note\n    // For real code use a node id, not hashCode().\n    while (!pq.isEmpty()) {\n        int[] cur = pq.poll();\n        if (cur[1] > dist.getOrDefault(String.valueOf(cur[0]), Integer.MAX_VALUE)) continue;\n        // ... standard relaxation over graph edges\n    }\n    return dist;\n}',
    'c++': '#include <queue>\n#include <unordered_map>\n#include <vector>\n#include <string>\n#include <limits>\n\nusing Graph = std::unordered_map<std::string, std::vector<std::pair<std::string, int>>>;\n\nstd::unordered_map<std::string, int> dijkstra(const Graph& graph, const std::string& start) {\n    std::unordered_map<std::string, int> dist;\n    for (const auto& [node, _] : graph) dist[node] = std::numeric_limits<int>::max();\n    dist[start] = 0;\n    using State = std::pair<int, std::string>;\n    std::priority_queue<State, std::vector<State>, std::greater<State>> pq;\n    pq.push({0, start});\n    while (!pq.empty()) {\n        auto [d, node] = pq.top();\n        pq.pop();\n        if (d > dist[node]) continue;\n        for (const auto& [neighbor, w] : graph.at(node)) {\n            if (int nd = d + w; nd < dist[neighbor]) {\n                dist[neighbor] = nd;\n                pq.push({nd, neighbor});\n            }\n        }\n    }\n    return dist;\n}',
    'c#': 'public static Dictionary<string, int> Dijkstra(\n    Dictionary<string, List<(string node, int weight)>> graph, string start)\n{\n    var dist = graph.Keys.ToDictionary(n => n, _ => int.MaxValue);\n    dist[start] = 0;\n    var pq = new PriorityQueue<(string node, int d), int>();\n    pq.Enqueue((start, 0), 0);\n    while (pq.TryDequeue(out var cur, out _))\n    {\n        if (cur.d > dist[cur.node]) continue;\n        foreach (var (neighbor, w) in graph[cur.node])\n        {\n            int nd = cur.d + w;\n            if (nd < dist[neighbor])\n            {\n                dist[neighbor] = nd;\n                pq.Enqueue((neighbor, nd), nd);\n            }\n        }\n    }\n    return dist;\n}',
})

add(d13, 'level_order', {
    'go': 'package main\n\ntype TreeNode struct {\n    Val   int\n    Left  *TreeNode\n    Right *TreeNode\n}\n\nfunc LevelOrder(root *TreeNode) [][]int {\n    if root == nil {\n        return nil\n    }\n    result := [][]int{}\n    queue := []*TreeNode{root}\n    for len(queue) > 0 {\n        level := []int{}\n        n := len(queue)\n        for i := 0; i < n; i++ {\n            node := queue[0]\n            queue = queue[1:]\n            level = append(level, node.Val)\n            if node.Left != nil {\n                queue = append(queue, node.Left)\n            }\n            if node.Right != nil {\n                queue = append(queue, node.Right)\n            }\n        }\n        result = append(result, level)\n    }\n    return result\n}',
    'rust': 'use std::collections::VecDeque;\n\n#[derive(Debug)]\npub struct TreeNode {\n    pub val: i32,\n    pub left: Option<Box<TreeNode>>,\n    pub right: Option<Box<TreeNode>>,\n}\n\npub fn level_order(root: Option<Box<TreeNode>>) -> Vec<Vec<i32>> {\n    let mut result = Vec::new();\n    let mut queue = VecDeque::new();\n    if let Some(r) = root { queue.push_back(r); }\n    while !queue.is_empty() {\n        let mut level = Vec::new();\n        for _ in 0..queue.len() {\n            if let Some(node) = queue.pop_front() {\n                level.push(node.val);\n                if let Some(l) = node.left { queue.push_back(l); }\n                if let Some(r) = node.right { queue.push_back(r); }\n            }\n        }\n        result.push(level);\n    }\n    result\n}',
    'java': 'import java.util.*;\n\npublic static List<List<Integer>> levelOrder(TreeNode root) {\n    List<List<Integer>> result = new ArrayList<>();\n    if (root == null) return result;\n    Queue<TreeNode> queue = new ArrayDeque<>();\n    queue.offer(root);\n    while (!queue.isEmpty()) {\n        List<Integer> level = new ArrayList<>();\n        for (int i = queue.size(); i > 0; i--) {\n            TreeNode node = queue.poll();\n            level.add(node.val);\n            if (node.left != null) queue.offer(node.left);\n            if (node.right != null) queue.offer(node.right);\n        }\n        result.add(level);\n    }\n    return result;\n}',
    'c++': '#include <vector>\n#include <queue>\n\nstruct TreeNode {\n    int val;\n    TreeNode *left, *right;\n    TreeNode(int v) : val(v), left(nullptr), right(nullptr) {}\n};\n\nstd::vector<std::vector<int>> levelOrder(TreeNode* root) {\n    std::vector<std::vector<int>> result;\n    if (!root) return result;\n    std::queue<TreeNode*> q;\n    q.push(root);\n    while (!q.empty()) {\n        std::vector<int> level;\n        for (int i = q.size(); i > 0; i--) {\n            TreeNode* node = q.front();\n            q.pop();\n            level.push_back(node->val);\n            if (node->left) q.push(node->left);\n            if (node->right) q.push(node->right);\n        }\n        result.push_back(level);\n    }\n    return result;\n}',
    'c#': 'public static List<List<int>> LevelOrder(TreeNode root)\n{\n    var result = new List<List<int>>();\n    if (root == null) return result;\n    var queue = new Queue<TreeNode>();\n    queue.Enqueue(root);\n    while (queue.Count > 0)\n    {\n        var level = new List<int>();\n        for (int i = queue.Count; i > 0; i--)\n        {\n            var node = queue.Dequeue();\n            level.Add(node.Val);\n            if (node.Left != null) queue.Enqueue(node.Left);\n            if (node.Right != null) queue.Enqueue(node.Right);\n        }\n        result.Add(level);\n    }\n    return result;\n}',
})

save('13_python_utils.json', d13)
save('15_ds_advanced.json', d15)

print('done')
